[CmdletBinding()]
param(
 [string]$AllowedParent='D:\DevCaches\georaeplan-private-artifacts',
 [Parameter(Mandatory=$true)][ValidatePattern('^[A-Fa-f0-9]{32}$')][string]$ArtifactId,
 [Parameter(Mandatory=$true)][string]$StagePath,
 [Parameter(Mandatory=$true)][ValidatePattern('^[A-Fa-f0-9]{32}$')][string]$ProducerRunId,
 [Parameter(Mandatory=$true)][string]$EvidenceOutputPath,
 [Parameter(Mandatory=$true)][string]$RepositoryRoot,
 [Parameter(Mandatory=$true)][string]$GitRemote,
 [Parameter(Mandatory=$true)][string]$GitRef,
 [Parameter(Mandatory=$true)][string]$ScopedPath,
 [ValidateSet('','AfterManifestPublish','MutateStageMarkerBeforeHandleBoundPublish','SwapStageNameBeforePublish','MutateFinalizeJournalBeforeMaterialization','SwapRemoteConfigBeforeLsRemote','PartialFinalizeJournalOneByte','PartialPayloadOneByte','PartialOwnerTail','PartialCompletionOneByte','RejectOwnedTestGateAfterExecution','FailAfterConsumerPostflight','FailStageCleanup','FailAfterFirstCleanupDisposition','MutateFinalTreeDuringCleanup','MutateVstestClosureDuringGate','CrashBeforeCleanupCommit','FailAfterFirstCleanupCommit','AddFinalChildAfterCommit')][string]$TestFaultInjection='',
 [switch]$Apply
)
Set-StrictMode -Version 2.0
$ErrorActionPreference='Stop'
. (Join-Path $PSScriptRoot 'GeoraePlanArtifactRetentionProducer.Common.ps1')
$script:GeoraePlanArtifactRetentionTestClosureManifestSha256='D396CD10B006F982FD6F06E3AAE79D66087A5E9D5DDA6BEE97400634DE4C9975'

function Invoke-GeoraePlanArtifactRetentionCheckedProcess {
 param([string]$Executable,[string[]]$Arguments,[string]$WorkingDirectory,[string]$Label,[switch]$AllowFailure)
 $previous=[Environment]::CurrentDirectory;$previousErrorAction=$ErrorActionPreference;$saved=@{};$childSystemDirectory=[Environment]::SystemDirectory;$childWindowsRoot=[IO.Path]::GetPathRoot($childSystemDirectory)+'Windows';$childTemp=[IO.Path]::GetTempPath().TrimEnd('\')
 try{
  foreach($entry in [Environment]::GetEnvironmentVariables().GetEnumerator()){$saved[[string]$entry.Key]=[string]$entry.Value;[Environment]::SetEnvironmentVariable([string]$entry.Key,$null)}
  $gitRoot=Split-Path -Parent (Split-Path -Parent $script:TrustedGitPath);$safePath=@($childSystemDirectory,(Join-Path $childSystemDirectory 'WindowsPowerShell\v1.0'),(Split-Path -Parent $script:TrustedDotnetPath),(Split-Path -Parent $script:TrustedGitPath),(Join-Path $gitRoot 'mingw64\bin')) -join ';'
  $safe=@{SystemRoot=$childWindowsRoot;WINDIR=$childWindowsRoot;ComSpec=(Join-Path $childSystemDirectory 'cmd.exe');TEMP=$childTemp;TMP=$childTemp;PATH=$safePath;PATHEXT='.COM;.EXE;.BAT;.CMD';DOTNET_ROOT=(Split-Path -Parent $script:TrustedDotnetPath);GIT_CONFIG_NOSYSTEM='1';GIT_CONFIG_GLOBAL='NUL';GIT_TERMINAL_PROMPT='0';GCM_INTERACTIVE='Never';DOTNET_CLI_UI_LANGUAGE='en-US';DOTNET_CLI_TELEMETRY_OPTOUT='1';DOTNET_SKIP_FIRST_TIME_EXPERIENCE='1';DOTNET_NOLOGO='1'}
  foreach($name in @('OS','SystemDrive','COMPUTERNAME','NUMBER_OF_PROCESSORS','PROCESSOR_ARCHITECTURE','PROCESSOR_IDENTIFIER','PROCESSOR_LEVEL','PROCESSOR_REVISION','ProgramData','ProgramFiles','ProgramFiles(x86)','CommonProgramFiles','CommonProgramFiles(x86)','USERPROFILE','HOMEDRIVE','HOMEPATH','APPDATA','LOCALAPPDATA','PUBLIC')){if($saved.ContainsKey($name)-and-not[string]::IsNullOrWhiteSpace([string]$saved[$name])){$safe[$name]=[string]$saved[$name]}}
  foreach($pair in $safe.GetEnumerator()){[Environment]::SetEnvironmentVariable($pair.Key,[string]$pair.Value)}
  if(-not[string]::IsNullOrWhiteSpace($WorkingDirectory)){[Environment]::CurrentDirectory=$WorkingDirectory}
  $ErrorActionPreference='Continue'
  $output=@(& $Executable @Arguments 2>&1);$exitCode=$LASTEXITCODE
 }finally{$ErrorActionPreference=$previousErrorAction;[Environment]::CurrentDirectory=$previous;foreach($entry in [Environment]::GetEnvironmentVariables().GetEnumerator()){[Environment]::SetEnvironmentVariable([string]$entry.Key,$null)};foreach($pair in $saved.GetEnumerator()){[Environment]::SetEnvironmentVariable([string]$pair.Key,[string]$pair.Value)}}
 if(-not$AllowFailure -and $exitCode -ne 0){throw "$Label failed."}
 return [pscustomobject]@{ExitCode=[int]$exitCode;Output=@($output|ForEach-Object{[string]$_})}
}
function Open-GeoraePlanArtifactRetentionTrustedTool {
 param([string]$Path,[string]$TrustedRoot,[string]$SignerPattern)
 $full=Get-GeoraePlanArtifactRetentionNormalizedPath $Path;$root=Get-GeoraePlanArtifactRetentionNormalizedPath $TrustedRoot
 if(-not(Test-GeoraePlanArtifactRetentionPathInside $root $full)){throw 'Trusted tool is outside its fixed installation root.'}
 Initialize-GeoraePlanArtifactRetentionProducerNativeType;$native=[GeoraePlan.ArtifactRetentionProducer.PinnedEntry]::OpenStableFile($full);$pin=$null
 try{$identity=$native.EntryIdentity;if($identity.IsDirectory -or $identity.IsReparsePoint -or -not(Test-GeoraePlanArtifactRetentionPathEquals $identity.FinalPath $full)){throw 'Trusted tool physical identity is invalid.'};$pin=[pscustomobject]@{Path=$full;PhysicalPath=(Get-GeoraePlanArtifactRetentionNormalizedPath $identity.FinalPath);VolumeSerialNumber=$identity.VolumeSerialNumber;FileId=$identity.FileId;NumberOfLinks=[uint32]$identity.Links;IsDirectory=$false;NativeHandle=$native};$native=$null;$signature=Get-AuthenticodeSignature -LiteralPath $full -ErrorAction Stop;if($signature.Status -ne [Management.Automation.SignatureStatus]::Valid -or [string]$signature.SignerCertificate.Subject -notmatch $SignerPattern){throw 'Trusted tool signature is invalid.'};Assert-GeoraePlanArtifactRetentionPinned $pin|Out-Null;return $pin}catch{Close-GeoraePlanArtifactRetentionPinned $pin;if($null-ne$native){$native.Dispose()};throw}
}
function Invoke-CheckedGit {
 param([string[]]$Arguments,[string]$Label)
 return (Invoke-GeoraePlanArtifactRetentionCheckedProcess $script:TrustedGitPath (@('-c','extensions.worktreeConfig=false','-C',$RepositoryRoot)+$Arguments) $RepositoryRoot $Label).Output
}
function Assert-GeoraePlanArtifactRetentionTrustedTestClosure {
 param($Manifest,$ClosureItems,$SourceLease,$ConsumerLease)
 Assert-GeoraePlanArtifactRetentionExactProperties $Manifest @('schemaVersion','kind','outputFileCount','outputDirectoryCount','entries') 'trusted test closure manifest'
 Assert-GeoraePlanArtifactRetentionJsonNonNegativeInteger $Manifest.schemaVersion 'trusted test closure schemaVersion';Assert-GeoraePlanArtifactRetentionJsonString $Manifest.kind 'trusted test closure kind';Assert-GeoraePlanArtifactRetentionJsonNonNegativeInteger $Manifest.outputFileCount 'trusted test closure outputFileCount';Assert-GeoraePlanArtifactRetentionJsonNonNegativeInteger $Manifest.outputDirectoryCount 'trusted test closure outputDirectoryCount';Assert-GeoraePlanArtifactRetentionJsonArray $Manifest.entries 'trusted test closure entries'
 if([int64]$Manifest.schemaVersion-ne1-or$Manifest.kind-cne'georaeplan-artifact-retention-test-closure-v1'-or[int64]$Manifest.outputFileCount-ne207-or[int64]$Manifest.outputDirectoryCount-ne65-or@($Manifest.entries).Count-ne274){throw 'Trusted test closure manifest inventory is invalid.'}
 $actual=New-Object 'Collections.Generic.Dictionary[string,object]' ([StringComparer]::Ordinal)
 $releaseFileCount=0;$releaseDirectoryCount=0
 foreach($item in @($ClosureItems)){$relative='release/'+([string]$item.relativePath).Replace('\','/');$entry=if($item.kind-ceq'directory'){$releaseDirectoryCount++;[pscustomobject][ordered]@{relativePath=$relative;kind='directory';length=$null;sha256=$null}}else{$releaseFileCount++;[pscustomobject][ordered]@{relativePath=$relative;kind='file';length=[int64]$item.length;sha256=[string]$item.sha256}};if($actual.ContainsKey($relative)){throw 'Test closure contains duplicate paths.'};$actual.Add($relative,$entry)}
 $sourceBytes=Read-GeoraePlanArtifactRetentionPinnedBytes $SourceLease;$consumerBytes=Read-GeoraePlanArtifactRetentionPinnedBytes $ConsumerLease
 $actual.Add('source/ArtifactRetentionSafetyTests.cs',[pscustomobject][ordered]@{relativePath='source/ArtifactRetentionSafetyTests.cs';kind='file';length=[int64]$sourceBytes.Length;sha256=(Get-GeoraePlanArtifactRetentionSha256 $sourceBytes)})
 $actual.Add('source/Invoke-GeoraePlanArtifactRetention.ps1',[pscustomobject][ordered]@{relativePath='source/Invoke-GeoraePlanArtifactRetention.ps1';kind='file';length=[int64]$consumerBytes.Length;sha256=(Get-GeoraePlanArtifactRetentionSha256 $consumerBytes)})
 if($releaseFileCount-ne[int64]$Manifest.outputFileCount-or$releaseDirectoryCount-ne[int64]$Manifest.outputDirectoryCount-or$actual.Count-ne@($Manifest.entries).Count){throw 'Current test closure inventory differs from the trusted manifest.'}
 $previous=$null
 foreach($expected in @($Manifest.entries)){
  Assert-GeoraePlanArtifactRetentionTestClosureEntrySchema $expected
  $relative=[string]$expected.relativePath;if($null-ne$previous-and[StringComparer]::Ordinal.Compare($previous,$relative)-ge0){throw 'Trusted test closure entries are not strictly ordinal sorted.'};$previous=$relative
  if($relative.Contains('\')-or$relative.StartsWith('/')-or@($relative.Split('/')|Where-Object{[string]::IsNullOrWhiteSpace($_)-or$_-in@('.','..')}).Count-ne0-or-not$actual.ContainsKey($relative)){throw 'Trusted test closure entry path is invalid.'}
  if((ConvertTo-GeoraePlanArtifactRetentionStrictJson $expected)-cne(ConvertTo-GeoraePlanArtifactRetentionStrictJson $actual[$relative])){throw 'Current test closure entry differs from the trusted manifest.'};[void]$actual.Remove($relative)
 }
 if($actual.Count-ne0){throw 'Current test closure contains untrusted entries.'}
}
function Invoke-GeoraePlanArtifactRetentionOwnedTestGate {
 $trustedSourceRoot=Get-GeoraePlanArtifactRetentionNormalizedPath (Join-Path $PSScriptRoot '..\..')
 $testOutput=Join-Path $trustedSourceRoot 'Tests\GeoraePlan.Desktop.App.Tests\bin\Release\net8.0-windows';$testAssembly=Join-Path $testOutput 'GeoraePlan.Desktop.App.Tests.dll';$testSource=Join-Path $trustedSourceRoot 'Tests\GeoraePlan.Desktop.App.Tests\ArtifactRetentionSafetyTests.cs';$manifestPath=Join-Path $PSScriptRoot 'GeoraePlanArtifactRetentionTestClosureManifest.json';$sourceLease=Open-GeoraePlanArtifactRetentionStableFile $testSource;$assemblyLease=$null;$manifestLease=$null;$closureRoot=$null;$closure=$null
 try{$manifestLease=Open-GeoraePlanArtifactRetentionStableFile $manifestPath;$manifestBytes=Read-GeoraePlanArtifactRetentionPinnedBytes $manifestLease;$closureManifestSha256=Get-GeoraePlanArtifactRetentionSha256 $manifestBytes;if($closureManifestSha256-cne$script:GeoraePlanArtifactRetentionTestClosureManifestSha256){throw 'Trusted test closure manifest hash is invalid.'};$manifest=Read-GeoraePlanArtifactRetentionPinnedStrictJson $manifestLease 'trusted test closure manifest';$closureRoot=Open-GeoraePlanArtifactRetentionPinned $testOutput -StableDirectory;$closure=Get-GeoraePlanArtifactRetentionExactClosurePlan $closureRoot;Assert-GeoraePlanArtifactRetentionTrustedTestClosure $manifest $closure.Items $sourceLease $consumerSourceLease;$sourceSha256=Get-GeoraePlanArtifactRetentionSha256 (Read-GeoraePlanArtifactRetentionPinnedBytes $sourceLease);$consumerSha256=Get-GeoraePlanArtifactRetentionSha256 (Read-GeoraePlanArtifactRetentionPinnedBytes $consumerSourceLease);$assemblyLease=Open-GeoraePlanArtifactRetentionStableFile $testAssembly;$assemblySha256=Get-GeoraePlanArtifactRetentionSha256 (Read-GeoraePlanArtifactRetentionPinnedBytes $assemblyLease);if($TestFaultInjection-eq'MutateVstestClosureDuringGate'){if($env:GEORAEPLAN_ARTIFACT_PRODUCER_TEST_MODE-ne'1'){throw 'Fault injection is test-mode only.'};$changed=$false;try{[IO.File]::AppendAllText((Join-Path $testOutput 'xunit.runner.visualstudio.testadapter.dll'),'x');$changed=$true}catch{};if($changed){throw 'Owned test execution closure changed.'}};$result=Invoke-GeoraePlanArtifactRetentionCheckedProcess $script:TrustedDotnetPath @('vstest',$testAssembly,'--TestCaseFilter:FullyQualifiedName~ArtifactRetentionSafetyTests','--Logger:console;verbosity=minimal') $trustedSourceRoot 'owned test gate' -AllowFailure;Assert-GeoraePlanArtifactRetentionPinned $manifestLease|Out-Null;Assert-GeoraePlanArtifactRetentionPinned $sourceLease|Out-Null;Assert-GeoraePlanArtifactRetentionPinned $consumerSourceLease|Out-Null;Assert-GeoraePlanArtifactRetentionPinned $assemblyLease|Out-Null;Assert-GeoraePlanArtifactRetentionExactClosurePlan $closureRoot $closure.Items;if((Get-GeoraePlanArtifactRetentionSha256 (Read-GeoraePlanArtifactRetentionPinnedBytes $manifestLease))-ine$closureManifestSha256-or(Get-GeoraePlanArtifactRetentionSha256 (Read-GeoraePlanArtifactRetentionPinnedBytes $assemblyLease)) -ine $assemblySha256 -or (Get-GeoraePlanArtifactRetentionSha256 (Read-GeoraePlanArtifactRetentionPinnedBytes $sourceLease)) -ine $sourceSha256 -or (Get-GeoraePlanArtifactRetentionSha256 (Read-GeoraePlanArtifactRetentionPinnedBytes $consumerSourceLease)) -ine $consumerSha256){throw 'Owned test gate inputs changed.'}}finally{Close-GeoraePlanArtifactRetentionPinned $assemblyLease;Close-GeoraePlanArtifactRetentionHeldTree $closure;Close-GeoraePlanArtifactRetentionPinned $closureRoot;Close-GeoraePlanArtifactRetentionPinned $manifestLease;Close-GeoraePlanArtifactRetentionPinned $sourceLease}
 if($result.ExitCode -ne 0){throw 'Owned test gate failed.'}
 $summaryLines=@($result.Output|Where-Object{$_ -match 'Failed:\s*(\d+),\s*Passed:\s*(\d+),\s*Skipped:\s*(\d+),\s*Total:\s*(\d+)'})
 if($summaryLines.Count -ne 1 -or $summaryLines[0] -notmatch 'Failed:\s*(\d+),\s*Passed:\s*(\d+),\s*Skipped:\s*(\d+),\s*Total:\s*(\d+)'){throw 'Owned test gate summary is missing.'}
 $summary=[pscustomobject]@{total=[int64]$matches[4];passed=[int64]$matches[2];failed=[int64]$matches[1];skipped=[int64]$matches[3]}
 Assert-GeoraePlanArtifactRetentionExactProperties $summary @('total','passed','failed','skipped') 'owned test gate summary'
 foreach($name in @('total','passed','failed','skipped')){Assert-GeoraePlanArtifactRetentionJsonNonNegativeInteger $summary.$name ('owned test gate '+$name)}
 if([decimal]$summary.total -ne 20 -or [decimal]$summary.passed -ne 20 -or [decimal]$summary.failed -ne 0 -or [decimal]$summary.skipped -ne 0){throw 'Owned test gate inventory is not exact.'}
 [Console]::Out.WriteLine("artifact_retention_test_gate=PASSED total=$($summary.total) passed=$($summary.passed) failed=$($summary.failed) skipped=$($summary.skipped)")
 Test-GeoraePlanArtifactRetentionFault 'RejectOwnedTestGateAfterExecution' $TestFaultInjection
 return [ordered]@{total=[int64]$summary.total;passed=[int64]$summary.passed;failed=[int64]$summary.failed;skipped=[int64]$summary.skipped;assemblySha256=$assemblySha256;sourceSha256=$sourceSha256;closureManifestSha256=$closureManifestSha256}
}
function Assert-GeoraePlanArtifactRetentionJsonArray {param($Value,[string]$Label)if($null-eq$Value -or -not$Value.GetType().IsArray){throw "$Label must be a JSON array."}}
function Assert-GeoraePlanArtifactRetentionJsonHex {param($Value,[int]$Length,[string]$Label)Assert-GeoraePlanArtifactRetentionJsonString $Value $Label;if(([string]$Value)-notmatch ('^[0-9A-Fa-f]{'+$Length+'}$')){throw "$Label is not exact hexadecimal metadata."}}
function Assert-GeoraePlanArtifactRetentionTestReceipt {
 param($Value,[string]$Label)
 Assert-GeoraePlanArtifactRetentionExactProperties $Value @('total','passed','failed','skipped','assemblySha256','sourceSha256','closureManifestSha256') $Label
 foreach($name in @('total','passed','failed','skipped')){Assert-GeoraePlanArtifactRetentionJsonNonNegativeInteger $Value.$name ($Label+' '+$name)}
 if([int64]$Value.total -ne 20 -or [int64]$Value.passed -ne 20 -or [int64]$Value.failed -ne 0 -or [int64]$Value.skipped -ne 0){throw "$Label inventory is invalid."}
 Assert-GeoraePlanArtifactRetentionJsonHex $Value.assemblySha256 64 ($Label+' assemblySha256');Assert-GeoraePlanArtifactRetentionJsonHex $Value.sourceSha256 64 ($Label+' sourceSha256');Assert-GeoraePlanArtifactRetentionJsonHex $Value.closureManifestSha256 64 ($Label+' closureManifestSha256');if([string]$Value.closureManifestSha256-ine$script:GeoraePlanArtifactRetentionTestClosureManifestSha256){throw "$Label trusted closure manifest hash is invalid."}
}
function Assert-GeoraePlanArtifactRetentionJournalPlan {
 param($Value)
 Assert-GeoraePlanArtifactRetentionJsonArray $Value 'FinalizeJournal materializationPlan';$seen=@{}
 foreach($item in $Value){Assert-GeoraePlanArtifactRetentionExactProperties $item @('relativePath','kind','length','sha256','volumeSerialNumber','fileId') 'FinalizeJournal plan item';foreach($field in @($item.relativePath,$item.kind,$item.volumeSerialNumber,$item.fileId)){Assert-GeoraePlanArtifactRetentionJsonString $field 'FinalizeJournal plan string'};Assert-GeoraePlanArtifactRetentionJsonNonNegativeInteger $item.length 'FinalizeJournal plan length';if($item.kind-cnotin@('directory','file')){throw 'FinalizeJournal plan kind is invalid.'};if($item.kind-ceq'directory'){if($null-ne$item.sha256 -or [int64]$item.length-ne0){throw 'FinalizeJournal directory metadata is invalid.'}}else{Assert-GeoraePlanArtifactRetentionJsonHex $item.sha256 64 'FinalizeJournal file sha256'};Assert-GeoraePlanArtifactRetentionJsonHex $item.volumeSerialNumber 8 'FinalizeJournal plan volume';Assert-GeoraePlanArtifactRetentionJsonHex $item.fileId 16 'FinalizeJournal plan fileId';if($seen.ContainsKey([string]$item.relativePath)){throw 'FinalizeJournal plan contains duplicate paths.'};$seen[[string]$item.relativePath]=$true}
}
function Assert-GeoraePlanArtifactRetentionCompletionShape {
 param($Value,[string]$Artifact)
 Assert-GeoraePlanArtifactRetentionExactProperties $Value @('schemaVersion','artifactId','outcome','testGate','gitPushGate','postflightGate','evidenceBundle','expectedEntries') 'completion marker';Assert-GeoraePlanArtifactRetentionJsonNonNegativeInteger $Value.schemaVersion 'completion schemaVersion';Assert-GeoraePlanArtifactRetentionJsonString $Value.artifactId 'completion artifactId';Assert-GeoraePlanArtifactRetentionJsonString $Value.outcome 'completion outcome';if([int64]$Value.schemaVersion -ne 1 -or $Value.artifactId -cne $Artifact -or $Value.outcome -cne 'succeeded'){throw 'Completion root metadata is invalid.'}
 foreach($gateName in @('testGate','postflightGate')){$gate=$Value.$gateName;Assert-GeoraePlanArtifactRetentionExactProperties $gate @('passed') ('completion '+$gateName);Assert-GeoraePlanArtifactRetentionJsonBoolean $gate.passed ('completion '+$gateName+' passed');if(-not$gate.passed){throw 'Completion gate failed.'}}
 Assert-GeoraePlanArtifactRetentionExactProperties $Value.gitPushGate @('passed','commitSha','remote') 'completion gitPushGate';Assert-GeoraePlanArtifactRetentionJsonBoolean $Value.gitPushGate.passed 'completion gitPushGate passed';if(-not$Value.gitPushGate.passed){throw 'Completion Git gate failed.'};Assert-GeoraePlanArtifactRetentionJsonHex $Value.gitPushGate.commitSha 40 'completion commit';Assert-GeoraePlanArtifactRetentionJsonString $Value.gitPushGate.remote 'completion remote'
 Assert-GeoraePlanArtifactRetentionExactProperties $Value.evidenceBundle @('path','sha256') 'completion evidenceBundle';Assert-GeoraePlanArtifactRetentionJsonString $Value.evidenceBundle.path 'completion evidence path';Assert-GeoraePlanArtifactRetentionJsonHex $Value.evidenceBundle.sha256 64 'completion evidence hash';Assert-GeoraePlanArtifactRetentionJsonArray $Value.expectedEntries 'completion expectedEntries'
 foreach($entry in $Value.expectedEntries){Assert-GeoraePlanArtifactRetentionExactProperties $entry @('relativePath','kind','sha256') 'completion expected entry';Assert-GeoraePlanArtifactRetentionJsonString $entry.relativePath 'completion relativePath';Assert-GeoraePlanArtifactRetentionJsonString $entry.kind 'completion entry kind';if($entry.kind-ceq'directory'){if($null-ne$entry.sha256){throw 'Completion directory hash must be null.'}}elseif($entry.kind-ceq'file'){Assert-GeoraePlanArtifactRetentionJsonHex $entry.sha256 64 'completion file hash'}else{throw 'Completion entry kind is invalid.'}}
}
function Get-GeoraePlanArtifactRetentionExistingCompletion {
 param($PinnedFinal)
 $children=New-Object Collections.Generic.List[object];$selected=$null
 try{
  foreach($record in @($PinnedFinal.NativeHandle.EnumerateAndOpenChildren($PinnedFinal.Path,'final-subset'))){$child=ConvertFrom-GeoraePlanArtifactRetentionNativeChild $PinnedFinal $record;if($record.Name -ceq $script:GeoraePlanArtifactRetentionCompletionFileName){if($child.IsDirectory -or $null -ne $selected){throw 'Completion marker identity is invalid.'};$selected=$child}else{[void]$children.Add($child)}}
  return $selected
 }catch{Close-GeoraePlanArtifactRetentionPinned $selected;throw}finally{foreach($child in $children){Close-GeoraePlanArtifactRetentionPinned $child}}
}
function Invoke-GeoraePlanArtifactRetentionConsumerDryRun {
 param([string]$ExpectedArtifactId,[switch]$SuppressOutput)
 $powershell=$script:TrustedPowerShellPath
 $consumer=Join-Path $PSScriptRoot 'Invoke-GeoraePlanArtifactRetention.ps1'
 $result=Invoke-GeoraePlanArtifactRetentionCheckedProcess $powershell @('-NoProfile','-ExecutionPolicy','Bypass','-File',$consumer,'-AllowedParent',$AllowedParent) $PSScriptRoot 'standalone retention consumer' -AllowFailure
 $idLine="artifact_retention=DRY_RUN artifact_id=$ExpectedArtifactId action=would_quarantine_and_purge"
 $summary=@($result.Output|Where-Object{$_ -match '^artifact_retention=DRY_RUN candidate_count=([0-9]+)$'})
 if($result.ExitCode -ne 0 -or @($result.Output|Where-Object{$_ -ceq $idLine}).Count -ne 1 -or $summary.Count -ne 1 -or $summary[0] -notmatch '^artifact_retention=DRY_RUN candidate_count=([0-9]+)$' -or [int64]$matches[1] -lt 1){throw 'Standalone retention consumer postflight failed.'}
 if(-not$SuppressOutput){foreach($line in $result.Output){Write-Output $line}}
}

$id=$ArtifactId.ToLowerInvariant();$runId=$ProducerRunId.ToLowerInvariant();$stageName='.georaeplan-producer-stage-'+$id;$finalizeName='.georaeplan-producer-finalize-'+$id+'.json'
$programFiles=[Environment]::GetFolderPath([Environment+SpecialFolder]::ProgramFiles);$systemDirectory=[Environment]::SystemDirectory
$script:TrustedDotnetPath=Join-Path $programFiles 'dotnet\dotnet.exe';$script:TrustedGitPath=Join-Path $programFiles 'Git\cmd\git.exe';$script:TrustedPowerShellPath=Join-Path $systemDirectory 'WindowsPowerShell\v1.0\powershell.exe'
$parent=$null;$repository=$null;$repositoryGitDirectory=$null;$gitConfigLease=$null;$remoteEndpointLease=$null;$dotnetToolLease=$null;$gitToolLease=$null;$powerShellToolLease=$null;$consumerSourceLease=$null;$stage=$null;$stageMarkerLease=$null;$journalLease=$null;$ownerLease=$null;$manifestLease=$null;$completionLease=$null;$evidenceLease=$null;$heldTree=$null;$final=$null;$lease=$null
$destinationLeases=New-Object Collections.Generic.List[object];$postPublication=$null
try{
 $dotnetToolLease=Open-GeoraePlanArtifactRetentionTrustedTool $script:TrustedDotnetPath (Join-Path $programFiles 'dotnet') 'Microsoft';$gitToolLease=Open-GeoraePlanArtifactRetentionTrustedTool $script:TrustedGitPath (Join-Path $programFiles 'Git') 'Schindelin';$powerShellToolLease=Open-GeoraePlanArtifactRetentionTrustedTool $script:TrustedPowerShellPath $systemDirectory 'Microsoft'
 $consumerSourceLease=Open-GeoraePlanArtifactRetentionStableFile (Join-Path $PSScriptRoot 'Invoke-GeoraePlanArtifactRetention.ps1')
 $parent=Assert-GeoraePlanArtifactRetentionParent $AllowedParent
 $stagePathFull=Get-GeoraePlanArtifactRetentionNormalizedPath $StagePath
 if(-not(Test-GeoraePlanArtifactRetentionPathEquals (Split-Path -Parent $stagePathFull) $parent.Path) -or (Split-Path -Leaf $stagePathFull) -cne $stageName){throw 'Stage path is not the exact expected direct child.'}
 $finalPath=Join-Path $parent.Path $id;$journalPath=Join-Path $parent.Path $finalizeName
 $repositoryPath=Get-GeoraePlanArtifactRetentionNormalizedPath $RepositoryRoot;if(-not(Test-Path -LiteralPath $repositoryPath -PathType Container)){throw 'Repository root is missing.'};$repository=Open-GeoraePlanArtifactRetentionPinned $repositoryPath
 $repositoryGitDirectory=Open-GeoraePlanArtifactRetentionPinned (Join-Path $repository.Path '.git') -StableDirectory;$gitConfigLease=Open-GeoraePlanArtifactRetentionStableFile (Join-Path $repositoryGitDirectory.Path 'config');$gitConfigSha256=Get-GeoraePlanArtifactRetentionSha256 (Read-GeoraePlanArtifactRetentionPinnedBytes $gitConfigLease)
 if($GitRemote -notmatch '^[A-Za-z0-9][A-Za-z0-9._-]{0,63}$' -or $GitRef -notmatch '^refs/heads/[A-Za-z0-9][A-Za-z0-9._/-]*$'){throw 'Git remote/ref is unsafe.'};$scope=$ScopedPath.Replace('\','/').Trim('/');if([string]::IsNullOrWhiteSpace($scope) -or [IO.Path]::IsPathRooted($ScopedPath) -or @($scope.Split('/')|Where-Object{$_ -eq '..' -or $_ -eq '.' -or [string]::IsNullOrWhiteSpace($_)}).Count -ne 0){throw 'Scoped path is unsafe.'}

 if(Test-Path -LiteralPath $finalPath -PathType Container){
  $final=Open-GeoraePlanArtifactRetentionRelativeEntry $parent.Identity $id $true;Assert-GeoraePlanArtifactRetentionPrivateAcl $final.Path
  $completionLease=Get-GeoraePlanArtifactRetentionExistingCompletion $final
  if($null -ne $completionLease){
   Assert-GeoraePlanArtifactRetentionPrivateFileAcl $completionLease.Path;$completionBytes=Read-GeoraePlanArtifactRetentionPinnedBytes $completionLease;Assert-GeoraePlanArtifactRetentionConsumerMetadataBytes $completionBytes
   try{$completion=Read-GeoraePlanArtifactRetentionPinnedStrictJson $completionLease 'completion marker'}catch{if(-not(Test-Path -LiteralPath $stagePathFull -PathType Container)){throw};Close-GeoraePlanArtifactRetentionPinned $completionLease;$completionLease=$null;$completion=$null}
   if($null -ne $completion){
    Assert-GeoraePlanArtifactRetentionCompletionShape $completion $id
    $journalLease=Open-GeoraePlanArtifactRetentionRelativeEntry $parent.Identity $finalizeName $false;Assert-GeoraePlanArtifactRetentionPrivateFileAcl $journalLease.Path;$journal=Read-GeoraePlanArtifactRetentionPinnedStrictJson $journalLease 'FinalizeJournal';$journalHash=Get-GeoraePlanArtifactRetentionSha256 (Read-GeoraePlanArtifactRetentionPinnedBytes $journalLease)
    Assert-GeoraePlanArtifactRetentionExactProperties $journal @('schemaVersion','kind','artifactId','producerRunId','stagePhysicalPath','stageFileId','stageVolumeSerialNumber','stageTokenSha256','stageMarkerSha256','stageMarkerVolumeSerialNumber','stageMarkerFileId','repositoryPhysicalPath','repositoryVolumeSerialNumber','repositoryFileId','evidenceSha256','evidencePath','commitSha','remote','gitRef','scopedPath','materializationPlan','createdAtUtc') 'FinalizeJournal'
    Assert-GeoraePlanArtifactRetentionJsonNonNegativeInteger $journal.schemaVersion 'FinalizeJournal schemaVersion';foreach($field in @($journal.kind,$journal.artifactId,$journal.producerRunId,$journal.stagePhysicalPath,$journal.repositoryPhysicalPath,$journal.evidencePath,$journal.remote,$journal.gitRef,$journal.scopedPath,$journal.createdAtUtc)){Assert-GeoraePlanArtifactRetentionJsonString $field 'FinalizeJournal string field'};foreach($field in @($journal.stageFileId,$journal.stageMarkerFileId,$journal.repositoryFileId)){Assert-GeoraePlanArtifactRetentionJsonHex $field 16 'FinalizeJournal fileId'};foreach($field in @($journal.stageVolumeSerialNumber,$journal.stageMarkerVolumeSerialNumber,$journal.repositoryVolumeSerialNumber)){Assert-GeoraePlanArtifactRetentionJsonHex $field 8 'FinalizeJournal volume'};foreach($field in @($journal.stageTokenSha256,$journal.stageMarkerSha256,$journal.evidenceSha256)){Assert-GeoraePlanArtifactRetentionJsonHex $field 64 'FinalizeJournal sha256'};Assert-GeoraePlanArtifactRetentionJsonHex $journal.commitSha 40 'FinalizeJournal commit';[void](ConvertFrom-GeoraePlanArtifactRetentionUtcTimestamp $journal.createdAtUtc 'FinalizeJournal createdAtUtc');Assert-GeoraePlanArtifactRetentionJournalPlan $journal.materializationPlan
    if([int64]$journal.schemaVersion -ne 1 -or $journal.kind -cne 'georaeplan-artifact-FinalizeJournal-v1' -or $journal.artifactId -cne $id -or $journal.producerRunId -cne $runId -or -not(Test-GeoraePlanArtifactRetentionPathEquals $journal.stagePhysicalPath $stagePathFull) -or $journal.remote -cne $GitRemote -or $journal.gitRef -cne $GitRef -or $journal.scopedPath -cne $scope -or -not(Test-GeoraePlanArtifactRetentionPathEquals $journal.repositoryPhysicalPath $repository.PhysicalPath) -or $journal.repositoryVolumeSerialNumber -ine $repository.VolumeSerialNumber -or $journal.repositoryFileId -ine $repository.FileId -or -not(Test-GeoraePlanArtifactRetentionPathEquals $journal.evidencePath (Get-GeoraePlanArtifactRetentionNormalizedPath $EvidenceOutputPath))){throw 'FinalizeJournal retry binding is invalid.'}
    $ownerLease=Open-GeoraePlanArtifactRetentionRelativeEntry $final $script:GeoraePlanArtifactRetentionOwnerFileName $false;$manifestLease=Open-GeoraePlanArtifactRetentionRelativeEntry $final $script:GeoraePlanArtifactRetentionProducerManifestFileName $false;Assert-GeoraePlanArtifactRetentionPrivateFileAcl $ownerLease.Path;Assert-GeoraePlanArtifactRetentionPrivateFileAcl $manifestLease.Path
    $existingOwner=Read-GeoraePlanArtifactRetentionPinnedStrictJson $ownerLease 'artifact owner';$existingManifest=Read-GeoraePlanArtifactRetentionPinnedStrictJson $manifestLease 'producer manifest'
    Assert-GeoraePlanArtifactRetentionExactProperties $existingOwner @('schemaVersion','owner','artifactId','createdAtUtc','rootPath','rootPhysicalPath','rootVolumeSerialNumber','rootFileId') 'artifact owner'
    Assert-GeoraePlanArtifactRetentionExactProperties $existingManifest @('schemaVersion','kind','artifactId','producerRunId','commitSha','remote','gitRef','scopedPath','repositoryPhysicalPath','repositoryVolumeSerialNumber','repositoryFileId','testSha256','postflightSha256','finalizeJournalSha256','createdAtUtc') 'producer manifest'
    Assert-GeoraePlanArtifactRetentionJsonNonNegativeInteger $existingOwner.schemaVersion 'owner schemaVersion';foreach($field in @($existingOwner.owner,$existingOwner.artifactId,$existingOwner.createdAtUtc,$existingOwner.rootPath,$existingOwner.rootPhysicalPath)){Assert-GeoraePlanArtifactRetentionJsonString $field 'owner string field'};Assert-GeoraePlanArtifactRetentionJsonHex $existingOwner.rootVolumeSerialNumber 8 'owner volume';Assert-GeoraePlanArtifactRetentionJsonHex $existingOwner.rootFileId 16 'owner fileId';[void](ConvertFrom-GeoraePlanArtifactRetentionUtcTimestamp $existingOwner.createdAtUtc 'owner createdAtUtc')
    Assert-GeoraePlanArtifactRetentionJsonNonNegativeInteger $existingManifest.schemaVersion 'manifest schemaVersion';foreach($field in @($existingManifest.kind,$existingManifest.artifactId,$existingManifest.producerRunId,$existingManifest.commitSha,$existingManifest.remote,$existingManifest.gitRef,$existingManifest.scopedPath,$existingManifest.repositoryPhysicalPath,$existingManifest.repositoryVolumeSerialNumber,$existingManifest.repositoryFileId,$existingManifest.testSha256,$existingManifest.postflightSha256,$existingManifest.finalizeJournalSha256,$existingManifest.createdAtUtc)){Assert-GeoraePlanArtifactRetentionJsonString $field 'manifest string field'};Assert-GeoraePlanArtifactRetentionJsonHex $existingManifest.commitSha 40 'manifest commit';Assert-GeoraePlanArtifactRetentionJsonHex $existingManifest.repositoryVolumeSerialNumber 8 'manifest volume';Assert-GeoraePlanArtifactRetentionJsonHex $existingManifest.repositoryFileId 16 'manifest fileId';foreach($field in @($existingManifest.testSha256,$existingManifest.postflightSha256,$existingManifest.finalizeJournalSha256)){Assert-GeoraePlanArtifactRetentionJsonHex $field 64 'manifest sha256'};[void](ConvertFrom-GeoraePlanArtifactRetentionUtcTimestamp $existingManifest.createdAtUtc 'manifest createdAtUtc')
    $existingManifestBytes=Read-GeoraePlanArtifactRetentionPinnedBytes $manifestLease;$expectedFromJournal=New-Object Collections.Generic.List[object];foreach($item in $journal.materializationPlan){[void]$expectedFromJournal.Add([ordered]@{relativePath=[string]$item.relativePath;kind=[string]$item.kind;sha256=$item.sha256})};$reconstructed=@(Get-GeoraePlanArtifactRetentionConsumerExpectedEntries $expectedFromJournal.ToArray() $existingManifestBytes)
    if((ConvertTo-GeoraePlanArtifactRetentionStrictJson $reconstructed) -cne (ConvertTo-GeoraePlanArtifactRetentionStrictJson $completion.expectedEntries) -or [int64]$existingOwner.schemaVersion -ne 1 -or $existingOwner.owner -cne $script:GeoraePlanArtifactRetentionArtifactOwnerKind -or $existingOwner.artifactId -cne $id -or -not(Test-GeoraePlanArtifactRetentionPathEquals $existingOwner.rootPath $final.Path) -or -not(Test-GeoraePlanArtifactRetentionPathEquals $existingOwner.rootPhysicalPath $final.PhysicalPath) -or $existingOwner.rootVolumeSerialNumber -ine $final.VolumeSerialNumber -or $existingOwner.rootFileId -ine $final.FileId -or [int64]$existingManifest.schemaVersion -ne 1 -or $existingManifest.kind -cne 'georaeplan-artifact-producer-manifest-v1' -or $existingManifest.artifactId -cne $id -or $existingManifest.producerRunId -cne $runId -or $existingManifest.commitSha -ine $journal.commitSha -or $existingManifest.remote -cne $GitRemote -or $existingManifest.gitRef -cne $GitRef -or $existingManifest.scopedPath -cne $scope -or -not(Test-GeoraePlanArtifactRetentionPathEquals $existingManifest.repositoryPhysicalPath $repository.PhysicalPath) -or $existingManifest.repositoryVolumeSerialNumber -ine $repository.VolumeSerialNumber -or $existingManifest.repositoryFileId -ine $repository.FileId -or $existingManifest.testSha256 -ine $journal.evidenceSha256 -or $existingManifest.postflightSha256 -ine $journal.evidenceSha256 -or $existingManifest.finalizeJournalSha256 -ine $journalHash -or $existingManifest.createdAtUtc -cne $journal.createdAtUtc -or $existingOwner.createdAtUtc -cne $journal.createdAtUtc -or $completion.gitPushGate.commitSha -ine $journal.commitSha -or $completion.gitPushGate.remote -cne $GitRemote -or -not(Test-GeoraePlanArtifactRetentionPathEquals $completion.evidenceBundle.path $journal.evidencePath) -or $completion.evidenceBundle.sha256 -ine $journal.evidenceSha256){throw 'Existing completion metadata cross-binding is invalid.'}
    $evidenceLease=Open-GeoraePlanArtifactRetentionStableFile ([string]$journal.evidencePath);Assert-GeoraePlanArtifactRetentionPrivateFileAcl $evidenceLease.Path;$evidenceBytes=Read-GeoraePlanArtifactRetentionPinnedBytes $evidenceLease
    if((Get-GeoraePlanArtifactRetentionSha256 $evidenceBytes) -ine [string]$journal.evidenceSha256){throw 'Existing evidence receipt hash is invalid.'};$existingEvidence=Read-GeoraePlanArtifactRetentionPinnedStrictJson $evidenceLease 'producer evidence';Assert-GeoraePlanArtifactRetentionExactProperties $existingEvidence @('schemaVersion','kind','artifactId','producerRunId','test','commitSha','createdAtUtc') 'producer evidence'
    Assert-GeoraePlanArtifactRetentionJsonNonNegativeInteger $existingEvidence.schemaVersion 'evidence schemaVersion';foreach($field in @($existingEvidence.kind,$existingEvidence.artifactId,$existingEvidence.producerRunId,$existingEvidence.commitSha,$existingEvidence.createdAtUtc)){Assert-GeoraePlanArtifactRetentionJsonString $field 'evidence string field'};Assert-GeoraePlanArtifactRetentionJsonHex $existingEvidence.commitSha 40 'evidence commit';[void](ConvertFrom-GeoraePlanArtifactRetentionUtcTimestamp $existingEvidence.createdAtUtc 'evidence createdAtUtc');Assert-GeoraePlanArtifactRetentionTestReceipt $existingEvidence.test 'evidence test receipt'
    if([int64]$existingEvidence.schemaVersion -ne 1 -or $existingEvidence.kind -cne 'georaeplan-artifact-producer-evidence-v1' -or $existingEvidence.artifactId -cne $id -or $existingEvidence.producerRunId -cne $runId -or $existingEvidence.commitSha -ine $journal.commitSha -or $existingEvidence.createdAtUtc -cne $journal.createdAtUtc){throw 'Existing evidence receipt binding is invalid.'}
    $postPublication=[pscustomobject]@{CommitSha=[string]$completion.gitPushGate.commitSha;Journal=$journal;JournalSha256=$journalHash;Existing=$true;ExpectedEntries=@($completion.expectedEntries);OwnerSha256=(Get-GeoraePlanArtifactRetentionSha256 (Read-GeoraePlanArtifactRetentionPinnedBytes $ownerLease));ManifestSha256=(Get-GeoraePlanArtifactRetentionSha256 (Read-GeoraePlanArtifactRetentionPinnedBytes $manifestLease));CompletionSha256=(Get-GeoraePlanArtifactRetentionSha256 $completionBytes);EvidenceSha256=[string]$journal.evidenceSha256}
   }
  }
 }

 if($null -eq $postPublication){
  $stage=Open-GeoraePlanArtifactRetentionRelativeEntry $parent.Identity $stageName $true;if(-not$stage.IsDirectory){throw 'Stage is not a directory.'};Assert-GeoraePlanArtifactRetentionPrivateAcl $stage.Path
  $stageTokenBytes=$stage.NativeHandle.ReadExtendedAttribute($script:GeoraePlanArtifactRetentionStageEaName);$stageTokenRaw=[Text.UTF8Encoding]::new($false,$true).GetString($stageTokenBytes);$stageToken=$stageTokenRaw|ConvertFrom-Json -ErrorAction Stop
  if($stageTokenRaw -cne (ConvertTo-GeoraePlanArtifactRetentionStrictJson $stageToken)){throw 'Stage provisioning token is noncanonical.'};Assert-GeoraePlanArtifactRetentionStageProvisioningToken $stageToken $id $parent.ParentId $stage.Path
  $stageMarkerLease=Open-GeoraePlanArtifactRetentionRelativeEntry $stage '.georaeplan-producer-stage.json' $false;Assert-GeoraePlanArtifactRetentionPrivateFileAcl $stageMarkerLease.Path
  $stageMeta=Read-GeoraePlanArtifactRetentionPinnedStrictJson $stageMarkerLease 'stage manifest';$stageMarkerBytes=Read-GeoraePlanArtifactRetentionPinnedBytes $stageMarkerLease;$stageMarkerSha256=Get-GeoraePlanArtifactRetentionSha256 $stageMarkerBytes
  Assert-GeoraePlanArtifactRetentionExactProperties $stageMeta @('schemaVersion','kind','artifactId','stagePath','stagePhysicalPath','stageVolumeSerialNumber','stageFileId','createdAtUtc') 'stage manifest'
  if($stageMeta.schemaVersion -ne 1 -or $stageMeta.kind -cne 'georaeplan-artifact-producer-stage-v1' -or $stageMeta.artifactId -cne $id -or $stageMeta.createdAtUtc -cne $stageToken.createdAtUtc -or -not(Test-GeoraePlanArtifactRetentionPathEquals $stageMeta.stagePath $stage.Path) -or -not(Test-GeoraePlanArtifactRetentionPathEquals $stageMeta.stagePhysicalPath $stage.PhysicalPath) -or $stageMeta.stageFileId -ine $stage.FileId -or $stageMeta.stageVolumeSerialNumber -ine $stage.VolumeSerialNumber){throw 'Stage manifest is not bound to the pinned stage.'}
  $heldTree=Get-GeoraePlanArtifactRetentionMaterializationPlan $stage;$plan=@($heldTree.Items);Assert-GeoraePlanArtifactRetentionConsumerPlan $plan;$journalPlan=@(Get-GeoraePlanArtifactRetentionJournalPlan $plan)

  if($GitRemote -notmatch '^[A-Za-z0-9][A-Za-z0-9._-]{0,63}$' -or $GitRef -notmatch '^refs/heads/[A-Za-z0-9][A-Za-z0-9._/-]*$'){throw 'Git remote/ref is unsafe.'}
  [void](Invoke-CheckedGit @('check-ref-format',$GitRef) 'git check-ref-format')
  $configKeys=Invoke-GeoraePlanArtifactRetentionCheckedProcess $script:TrustedGitPath @('config','--file',$gitConfigLease.Path,'--no-includes','--name-only','--list') $systemDirectory 'git config key inspection'
  foreach($configKey in @($configKeys.Output)){
   if([string]::IsNullOrWhiteSpace([string]$configKey)){throw 'Git repository config contains an invalid key name.'}
   $normalizedConfigKey=([string]$configKey).Trim().ToLowerInvariant()
   if($normalizedConfigKey -match '^(include\.|includeif\.|url\..*\.(insteadof|pushinsteadof)$|credential\.|core\.(sshcommand|askpass|gitproxy)$|remote\..*\.proxy$|http\.)'){throw 'Git repository contains unsafe redirect or credential configuration.'}
  }
  $remoteCapture=Invoke-GeoraePlanArtifactRetentionCheckedProcess $script:TrustedGitPath @('config','--no-includes','--file',$gitConfigLease.Path,'--get-all',('remote.'+$GitRemote+'.url')) $systemDirectory 'git remote URL capture';$remoteUrls=@($remoteCapture.Output);if($remoteUrls.Count -ne 1 -or [string]::IsNullOrWhiteSpace([string]$remoteUrls[0])){throw 'Git remote must resolve to one endpoint.'};$remoteText=([string]$remoteUrls[0]).Trim()
  if($remoteText.Contains('@')){throw 'Git remote embedded credentials are forbidden.'};if([IO.Path]::IsPathRooted($remoteText)){$remoteLocal=Get-GeoraePlanArtifactRetentionNormalizedPath $remoteText;if(-not(Test-Path -LiteralPath $remoteLocal -PathType Container)){throw 'Git local remote is missing.'};$remoteEndpointLease=Open-GeoraePlanArtifactRetentionPinned $remoteLocal -StableDirectory}else{$remoteUri=$null;if(-not[Uri]::TryCreate($remoteText,[UriKind]::Absolute,[ref]$remoteUri) -or -not[string]::IsNullOrEmpty($remoteUri.UserInfo) -or -not[string]::IsNullOrEmpty($remoteUri.Query) -or -not[string]::IsNullOrEmpty($remoteUri.Fragment)){throw 'Git remote URL is unsafe.'};if($remoteUri.IsFile){$remoteLocal=Get-GeoraePlanArtifactRetentionNormalizedPath $remoteUri.LocalPath;if(-not(Test-Path -LiteralPath $remoteLocal -PathType Container)){throw 'Git file remote is missing.'};$remoteEndpointLease=Open-GeoraePlanArtifactRetentionPinned $remoteLocal -StableDirectory}elseif($remoteUri.Scheme -cne 'https' -or [string]::IsNullOrWhiteSpace($remoteUri.Host)){throw 'Git remote URL scheme/host is unsafe.'}}
  $sha=([string](@(Invoke-CheckedGit @('rev-parse','--verify','HEAD^{commit}') 'git rev-parse')[0])).Trim().ToUpperInvariant();if($sha -notmatch '^[0-9A-F]{40}$'){throw 'Git commit OID is invalid.'}
  if($TestFaultInjection -eq 'SwapRemoteConfigBeforeLsRemote'){if($env:GEORAEPLAN_ARTIFACT_PRODUCER_TEST_MODE -ne '1'){throw 'Fault injection is test-mode only.'};$blocked=Invoke-GeoraePlanArtifactRetentionCheckedProcess $script:TrustedGitPath @('-C',$RepositoryRoot,'remote','set-url',$GitRemote,'https://invalid.example/replaced.git') $RepositoryRoot 'git remote swap hook' -AllowFailure;if($blocked.ExitCode -eq 0){throw 'Pinned Git config mutation unexpectedly succeeded.'}}
  Assert-GeoraePlanArtifactRetentionPinned $gitConfigLease|Out-Null;if((Get-GeoraePlanArtifactRetentionSha256 (Read-GeoraePlanArtifactRetentionPinnedBytes $gitConfigLease)) -ine $gitConfigSha256){throw 'Pinned Git config changed.'};if($null-ne$remoteEndpointLease){Assert-GeoraePlanArtifactRetentionPinned $remoteEndpointLease|Out-Null}
  $remoteResult=@((Invoke-GeoraePlanArtifactRetentionCheckedProcess $script:TrustedGitPath @('ls-remote','--exit-code','--refs',$remoteText,$GitRef) $systemDirectory 'git ls-remote --exit-code --refs').Output);if($remoteResult.Count -ne 1 -or ([string]$remoteResult[0]) -notmatch '^([0-9a-fA-F]{40})\s+(.+)$' -or $matches[1].ToUpperInvariant() -cne $sha -or $matches[2] -cne $GitRef){throw 'Git remote ref does not resolve to the exact candidate OID.'}
  Assert-GeoraePlanArtifactRetentionPinned $gitConfigLease|Out-Null;if((Get-GeoraePlanArtifactRetentionSha256 (Read-GeoraePlanArtifactRetentionPinnedBytes $gitConfigLease)) -ine $gitConfigSha256){throw 'Pinned Git config changed during proof.'};if($null-ne$remoteEndpointLease){Assert-GeoraePlanArtifactRetentionPinned $remoteEndpointLease|Out-Null}
  $scope=$ScopedPath.Replace('\','/').Trim('/');if([string]::IsNullOrWhiteSpace($scope) -or [IO.Path]::IsPathRooted($ScopedPath) -or @($scope.Split('/')|Where-Object{$_ -eq '..' -or $_ -eq '.' -or [string]::IsNullOrWhiteSpace($_)}).Count -ne 0){throw 'Scoped path is unsafe.'}
  $changed=@(Invoke-CheckedGit @('diff-tree','--root','--no-commit-id','--name-only','-r',$sha,'--') 'git scoped changed paths'|Where-Object{-not[string]::IsNullOrWhiteSpace([string]$_)});if($changed.Count -ne 1 -or ([string]$changed[0]).Replace('\','/') -cne $scope){throw 'Git commit changed paths are outside the exact requested scope.'}
  $testSummary=Invoke-GeoraePlanArtifactRetentionOwnedTestGate
  $createdAt=[string]$stageToken.createdAtUtc;$evidence=[ordered]@{schemaVersion=1;kind='georaeplan-artifact-producer-evidence-v1';artifactId=$id;producerRunId=$runId;test=$testSummary;commitSha=$sha;createdAtUtc=$createdAt};$evidenceBytes=[Text.UTF8Encoding]::new($false).GetBytes((ConvertTo-GeoraePlanArtifactRetentionStrictJson $evidence));$evidenceSha=Get-GeoraePlanArtifactRetentionSha256 $evidenceBytes
  $producerManifest=[ordered]@{schemaVersion=1;kind='georaeplan-artifact-producer-manifest-v1';artifactId=$id;producerRunId=$runId;commitSha=$sha;remote=$GitRemote;gitRef=$GitRef;scopedPath=$scope;repositoryPhysicalPath=$repository.PhysicalPath;repositoryVolumeSerialNumber=$repository.VolumeSerialNumber;repositoryFileId=$repository.FileId;testSha256=$evidenceSha;postflightSha256=$evidenceSha;finalizeJournalSha256=('0'*64);createdAtUtc=$createdAt};$manifestBytes=[Text.UTF8Encoding]::new($false).GetBytes((ConvertTo-GeoraePlanArtifactRetentionStrictJson $producerManifest))
  $completion=[ordered]@{schemaVersion=1;artifactId=$id;outcome='succeeded';testGate=[ordered]@{passed=$true};gitPushGate=[ordered]@{passed=$true;commitSha=$sha;remote=$GitRemote};postflightGate=[ordered]@{passed=$true};evidenceBundle=[ordered]@{path=(Get-GeoraePlanArtifactRetentionNormalizedPath $EvidenceOutputPath);sha256=$evidenceSha};expectedEntries=@(Get-GeoraePlanArtifactRetentionConsumerExpectedEntries $plan $manifestBytes)};$completionBytes=[Text.UTF8Encoding]::new($false).GetBytes((ConvertTo-GeoraePlanArtifactRetentionStrictJson $completion));Assert-GeoraePlanArtifactRetentionConsumerMetadataBytes $completionBytes
  if(-not$Apply -and $null -ne $final){$dryJournal=$null;try{if(-not(Test-Path -LiteralPath $journalPath -PathType Leaf)){throw 'An unowned partial canonical artifact cannot be adopted.'};$dryJournal=Open-GeoraePlanArtifactRetentionRelativeEntry $parent.Identity $finalizeName $false;$dryBinding=Read-GeoraePlanArtifactRetentionPinnedStrictJson $dryJournal 'FinalizeJournal';if($dryBinding.artifactId -cne $id -or $dryBinding.producerRunId -cne $runId -or $dryBinding.repositoryVolumeSerialNumber -ine $repository.VolumeSerialNumber -or $dryBinding.repositoryFileId -ine $repository.FileId){throw 'Dry-run partial artifact binding is invalid.'};Assert-GeoraePlanArtifactRetentionFinalSubset $final $plan @(Get-GeoraePlanArtifactRetentionFinalMetadataNames)}finally{Close-GeoraePlanArtifactRetentionPinned $dryJournal}}
  $evidenceOutputFull=Get-GeoraePlanArtifactRetentionNormalizedPath $EvidenceOutputPath;$evidenceParentPath=Split-Path -Parent $evidenceOutputFull;if((Test-GeoraePlanArtifactRetentionPathEquals $evidenceParentPath $parent.Path) -or (Test-GeoraePlanArtifactRetentionPathInside $parent.Path $evidenceParentPath) -or (Test-GeoraePlanArtifactRetentionPathEquals $evidenceParentPath $repository.PhysicalPath) -or (Test-GeoraePlanArtifactRetentionPathInside $repository.PhysicalPath $evidenceParentPath)){throw 'Evidence output must be external to the repository and artifact parent.'}
  $evidencePreflightParent=$null;$evidencePreflightFile=$null;$preflightLease=$null;try{$evidencePreflightParent=Open-GeoraePlanArtifactRetentionPinned $evidenceParentPath -StableDirectory;Assert-GeoraePlanArtifactRetentionPrivateAcl $evidencePreflightParent.Path;if(Test-Path -LiteralPath $evidenceOutputFull){$evidencePreflightFile=Open-GeoraePlanArtifactRetentionRelativeEntry $evidencePreflightParent (Split-Path -Leaf $evidenceOutputFull) $false;Assert-GeoraePlanArtifactRetentionPrivateFileAcl $evidencePreflightFile.Path;$actualEvidence=Read-GeoraePlanArtifactRetentionPinnedBytes $evidencePreflightFile;if($actualEvidence.Length-gt$evidenceBytes.Length){throw 'Evidence output is not an exact resumable prefix.'};for($index=0;$index-lt$actualEvidence.Length;$index++){if($actualEvidence[$index]-ne$evidenceBytes[$index]){throw 'Evidence output is not an exact resumable prefix.'}}};$preflightLease=Enter-GeoraePlanArtifactRetentionProducerLease $parent.LeasePath;Assert-GeoraePlanArtifactRetentionParentUnchanged $parent $parent.MarkerSha256 $preflightLease}finally{if($null-ne$preflightLease){$preflightLease.Dispose()};Close-GeoraePlanArtifactRetentionPinned $evidencePreflightFile;Close-GeoraePlanArtifactRetentionPinned $evidencePreflightParent}
  if(-not$Apply){Write-Output "artifact_retention_completion=DRY_RUN action=would_finalize artifact_id=$id";return}

  $evidenceParent=Open-GeoraePlanArtifactRetentionPinned $evidenceParentPath -StableDirectory;try{Assert-GeoraePlanArtifactRetentionPrivateAcl $evidenceParent.Path;$evidenceLease=Write-GeoraePlanArtifactRetentionRelativeCreateNewBytes $evidenceParent (Split-Path -Leaf $EvidenceOutputPath) $evidenceBytes}finally{Close-GeoraePlanArtifactRetentionPinned $evidenceParent}

  $lease=Enter-GeoraePlanArtifactRetentionProducerLease $parent.LeasePath;Assert-GeoraePlanArtifactRetentionParentUnchanged $parent $parent.MarkerSha256 $lease
  if((Test-Path -LiteralPath $finalPath) -and -not(Test-Path -LiteralPath $journalPath -PathType Leaf)){throw 'An unowned partial canonical artifact cannot be adopted.'}
  $binding=[ordered]@{schemaVersion=1;kind='georaeplan-artifact-FinalizeJournal-v1';artifactId=$id;producerRunId=$runId;stagePhysicalPath=$stage.PhysicalPath;stageFileId=$stage.FileId;stageVolumeSerialNumber=$stage.VolumeSerialNumber;stageTokenSha256=(Get-GeoraePlanArtifactRetentionSha256 $stageTokenBytes);stageMarkerSha256=$stageMarkerSha256;stageMarkerVolumeSerialNumber=$stageMarkerLease.VolumeSerialNumber;stageMarkerFileId=$stageMarkerLease.FileId;repositoryPhysicalPath=$repository.PhysicalPath;repositoryVolumeSerialNumber=$repository.VolumeSerialNumber;repositoryFileId=$repository.FileId;evidenceSha256=$evidenceSha;evidencePath=(Get-GeoraePlanArtifactRetentionNormalizedPath $EvidenceOutputPath);commitSha=$sha;remote=$GitRemote;gitRef=$GitRef;scopedPath=$scope;materializationPlan=@($journalPlan);createdAtUtc=$createdAt}
  $journalBytes=[Text.UTF8Encoding]::new($false).GetBytes((ConvertTo-GeoraePlanArtifactRetentionStrictJson $binding));$journalPartial=if($TestFaultInjection -eq 'PartialFinalizeJournalOneByte' -and -not(Test-Path -LiteralPath $journalPath)){1}else{-1};$journalLease=Write-GeoraePlanArtifactRetentionRelativeCreateNewBytes $parent.Identity $finalizeName $journalBytes $journalPartial;Assert-GeoraePlanArtifactRetentionExactJson (Read-GeoraePlanArtifactRetentionPinnedStrictJson $journalLease 'FinalizeJournal') $binding 'FinalizeJournal';$journalSha=Get-GeoraePlanArtifactRetentionSha256 (Read-GeoraePlanArtifactRetentionPinnedBytes $journalLease)
  $producerManifest.finalizeJournalSha256=$journalSha;$manifestBytes=[Text.UTF8Encoding]::new($false).GetBytes((ConvertTo-GeoraePlanArtifactRetentionStrictJson $producerManifest));$completion.expectedEntries=@(Get-GeoraePlanArtifactRetentionConsumerExpectedEntries $plan $manifestBytes);$completionBytes=[Text.UTF8Encoding]::new($false).GetBytes((ConvertTo-GeoraePlanArtifactRetentionStrictJson $completion));Assert-GeoraePlanArtifactRetentionConsumerMetadataBytes $completionBytes
  if($TestFaultInjection -eq 'MutateFinalizeJournalBeforeMaterialization'){Add-Content -LiteralPath $journalLease.Path -Value ' ';throw 'Injected FinalizeJournal mutation.'}
  [void](Invoke-GeoraePlanArtifactRetentionTestStageSwap $stagePathFull $stage $finalPath $TestFaultInjection);if($TestFaultInjection -eq 'MutateStageMarkerBeforeHandleBoundPublish'){Add-Content -LiteralPath $stageMarkerLease.Path -Value ' ';throw 'Injected stage mutation.'}
  Assert-GeoraePlanArtifactRetentionMaterializationPlan $stage $plan
  if($null -eq $final){if(Test-Path -LiteralPath $finalPath){$final=Open-GeoraePlanArtifactRetentionRelativeEntry $parent.Identity $id $true;Assert-GeoraePlanArtifactRetentionPrivateAcl $final.Path}else{$final=New-GeoraePlanArtifactRetentionRelativeDirectory $parent.Identity $id}}
  Invoke-GeoraePlanArtifactRetentionMaterialization $stage $final $plan $destinationLeases $TestFaultInjection
  $owner=[ordered]@{schemaVersion=1;owner=$script:GeoraePlanArtifactRetentionArtifactOwnerKind;artifactId=$id;createdAtUtc=$createdAt;rootPath=$final.Path;rootPhysicalPath=$final.PhysicalPath;rootVolumeSerialNumber=$final.VolumeSerialNumber;rootFileId=$final.FileId};$ownerBytes=[Text.UTF8Encoding]::new($false).GetBytes((ConvertTo-GeoraePlanArtifactRetentionStrictJson $owner));$ownerPartial=if($TestFaultInjection -eq 'PartialOwnerTail' -and -not(Test-Path -LiteralPath (Join-Path $final.Path $script:GeoraePlanArtifactRetentionOwnerFileName))){$ownerBytes.Length-1}else{-1};$ownerLease=Write-GeoraePlanArtifactRetentionRelativeCreateNewBytes $final $script:GeoraePlanArtifactRetentionOwnerFileName $ownerBytes $ownerPartial;Assert-GeoraePlanArtifactRetentionExactJson (Read-GeoraePlanArtifactRetentionPinnedStrictJson $ownerLease 'artifact owner') $owner 'artifact owner'
  $manifestLease=Write-GeoraePlanArtifactRetentionRelativeCreateNewBytes $final $script:GeoraePlanArtifactRetentionProducerManifestFileName $manifestBytes;Assert-GeoraePlanArtifactRetentionExactJson (Read-GeoraePlanArtifactRetentionPinnedStrictJson $manifestLease 'producer manifest') $producerManifest 'producer manifest'
  if((Get-GeoraePlanArtifactRetentionSha256 (Read-GeoraePlanArtifactRetentionPinnedBytes $journalLease)) -ine $journalSha -or (Get-GeoraePlanArtifactRetentionSha256 (Read-GeoraePlanArtifactRetentionPinnedBytes $stageMarkerLease)) -ine $stageMarkerSha256 -or (Get-GeoraePlanArtifactRetentionSha256 $stage.NativeHandle.ReadExtendedAttribute($script:GeoraePlanArtifactRetentionStageEaName)) -ine $binding.stageTokenSha256){throw 'Held producer metadata changed before completion.'}
  Test-GeoraePlanArtifactRetentionFault 'AfterManifestPublish' $TestFaultInjection;Assert-GeoraePlanArtifactRetentionMaterializationPlan $stage $plan;Assert-GeoraePlanArtifactRetentionFinalSubset $final $plan @(Get-GeoraePlanArtifactRetentionFinalMetadataNames);Assert-GeoraePlanArtifactRetentionParentUnchanged $parent $parent.MarkerSha256 $lease
  $completionPartial=if($TestFaultInjection -eq 'PartialCompletionOneByte' -and -not(Test-Path -LiteralPath (Join-Path $final.Path $script:GeoraePlanArtifactRetentionCompletionFileName))){1}else{-1};$completionLease=Write-GeoraePlanArtifactRetentionRelativeCreateNewBytes $final $script:GeoraePlanArtifactRetentionCompletionFileName $completionBytes $completionPartial;Assert-GeoraePlanArtifactRetentionExactJson (Read-GeoraePlanArtifactRetentionPinnedStrictJson $completionLease 'completion marker') $completion 'completion marker'
  $postPublication=[pscustomobject]@{CommitSha=$sha;Journal=$binding;JournalSha256=$journalSha;Existing=$false;ExpectedEntries=@($completion.expectedEntries);OwnerSha256=(Get-GeoraePlanArtifactRetentionSha256 $ownerBytes);ManifestSha256=(Get-GeoraePlanArtifactRetentionSha256 $manifestBytes);CompletionSha256=(Get-GeoraePlanArtifactRetentionSha256 $completionBytes);EvidenceSha256=$evidenceSha}
 }
}finally{
 if($null -ne $lease){$lease.Dispose()};for($i=$destinationLeases.Count-1;$i -ge 0;$i--){Close-GeoraePlanArtifactRetentionPinned $destinationLeases[$i]};Close-GeoraePlanArtifactRetentionHeldTree $heldTree
  Close-GeoraePlanArtifactRetentionPinned $completionLease;Close-GeoraePlanArtifactRetentionPinned $manifestLease;Close-GeoraePlanArtifactRetentionPinned $ownerLease;Close-GeoraePlanArtifactRetentionPinned $journalLease;Close-GeoraePlanArtifactRetentionPinned $evidenceLease;Close-GeoraePlanArtifactRetentionPinned $stageMarkerLease;Close-GeoraePlanArtifactRetentionPinned $final;Close-GeoraePlanArtifactRetentionPinned $remoteEndpointLease;Close-GeoraePlanArtifactRetentionPinned $gitConfigLease;Close-GeoraePlanArtifactRetentionPinned $repositoryGitDirectory;Close-GeoraePlanArtifactRetentionPinned $repository;Close-GeoraePlanArtifactRetentionPinned $stage;Close-GeoraePlanArtifactRetentionParent $parent
}

if(-not$Apply -and $null-ne$postPublication){Invoke-GeoraePlanArtifactRetentionConsumerDryRun $id;Write-Output "artifact_retention_completion=DRY_RUN action=already_completed artifact_id=$id"}
if($Apply -and $null -ne $postPublication){
 $cleanupParent=$null;$cleanupLease=$null;$cleanupPlan=$null;$cleanupJournal=$null;$cleanupFinal=$null;$cleanupOwner=$null;$cleanupManifest=$null;$cleanupCompletion=$null;$cleanupEvidence=$null;$cleanupTree=$null
 try{
  $cleanupParent=Assert-GeoraePlanArtifactRetentionParent $AllowedParent;$cleanupParentBinding=[pscustomobject]@{VolumeSerialNumber=$cleanupParent.Identity.VolumeSerialNumber;FileId=$cleanupParent.Identity.FileId;MarkerSha256=$cleanupParent.MarkerSha256;BootstrapSha256=$cleanupParent.BootstrapSha256};$cleanupLease=Enter-GeoraePlanArtifactRetentionProducerLease $cleanupParent.LeasePath;Assert-GeoraePlanArtifactRetentionParentUnchanged $cleanupParent $cleanupParent.MarkerSha256 $cleanupLease
  $cleanupFinal=Open-GeoraePlanArtifactRetentionRelativeEntry $cleanupParent.Identity $id $true;$cleanupOwner=Open-GeoraePlanArtifactRetentionRelativeEntry $cleanupFinal $script:GeoraePlanArtifactRetentionOwnerFileName $false;$cleanupManifest=Open-GeoraePlanArtifactRetentionRelativeEntry $cleanupFinal $script:GeoraePlanArtifactRetentionProducerManifestFileName $false;$cleanupCompletion=Open-GeoraePlanArtifactRetentionRelativeEntry $cleanupFinal $script:GeoraePlanArtifactRetentionCompletionFileName $false;$cleanupEvidence=Open-GeoraePlanArtifactRetentionStableFile ([string]$postPublication.Journal.evidencePath);$cleanupTree=Get-GeoraePlanArtifactRetentionHeldFinalConsumerTree $cleanupFinal @($postPublication.ExpectedEntries);if((Get-GeoraePlanArtifactRetentionSha256 (Read-GeoraePlanArtifactRetentionPinnedBytes $cleanupOwner)) -ine $postPublication.OwnerSha256 -or (Get-GeoraePlanArtifactRetentionSha256 (Read-GeoraePlanArtifactRetentionPinnedBytes $cleanupManifest)) -ine $postPublication.ManifestSha256 -or (Get-GeoraePlanArtifactRetentionSha256 (Read-GeoraePlanArtifactRetentionPinnedBytes $cleanupCompletion)) -ine $postPublication.CompletionSha256 -or (Get-GeoraePlanArtifactRetentionSha256 (Read-GeoraePlanArtifactRetentionPinnedBytes $cleanupEvidence)) -ine $postPublication.EvidenceSha256){throw 'Completed artifact metadata changed before stage cleanup.'}
   if($TestFaultInjection -eq 'FailStageCleanup'){Test-GeoraePlanArtifactRetentionFault 'FailStageCleanup' $TestFaultInjection}
   $journal=$postPublication.Journal;$stageIdentity=[pscustomobject]@{VolumeSerialNumber=[string]$journal.stageVolumeSerialNumber;FileId=[string]$journal.stageFileId;TokenSha256=[string]$journal.stageTokenSha256}
   $cleanupPlan=New-GeoraePlanArtifactRetentionHeldStageCleanupPlan $cleanupParent $cleanupLease $stageName $stageIdentity @($journal.materializationPlan) ([string]$journal.stageMarkerSha256) ([string]$journal.stageMarkerVolumeSerialNumber) ([string]$journal.stageMarkerFileId) -AllowMissing:$postPublication.Existing
   if($TestFaultInjection-eq'FailAfterFirstCleanupDisposition'){throw 'Injected failure before first cleanup disposition.'}
   if($TestFaultInjection -eq 'MutateFinalTreeDuringCleanup'){$target=@($postPublication.ExpectedEntries|Where-Object{$_.kind-ceq'file'-and$_.relativePath-cne$script:GeoraePlanArtifactRetentionProducerManifestFileName}|Select-Object -First 1);if($target.Count-ne1){throw 'Cleanup mutation fixture target is unavailable.'};$changed=$false;try{[IO.File]::AppendAllText((Join-Path $cleanupFinal.Path ([string]$target[0].relativePath.Replace('/','\'))),'x');$changed=$true}catch{};if($changed){throw 'Completed artifact changed during cleanup.'}}
   Close-GeoraePlanArtifactRetentionHeldTree $cleanupTree;$cleanupTree=$null;Close-GeoraePlanArtifactRetentionPinned $cleanupEvidence;$cleanupEvidence=$null;Close-GeoraePlanArtifactRetentionPinned $cleanupCompletion;$cleanupCompletion=$null;Close-GeoraePlanArtifactRetentionPinned $cleanupManifest;$cleanupManifest=$null;Close-GeoraePlanArtifactRetentionPinned $cleanupOwner;$cleanupOwner=$null;Close-GeoraePlanArtifactRetentionPinned $cleanupFinal;$cleanupFinal=$null
   $cleanupLease.Dispose();$cleanupLease=$null;Close-GeoraePlanArtifactRetentionParent $cleanupParent;$cleanupParent=$null
   Invoke-GeoraePlanArtifactRetentionConsumerDryRun $id -SuppressOutput
   Test-GeoraePlanArtifactRetentionFault 'FailAfterConsumerPostflight' $TestFaultInjection
   if($TestFaultInjection-eq'CrashBeforeCleanupCommit'){if($env:GEORAEPLAN_ARTIFACT_PRODUCER_TEST_MODE-ne'1'){throw 'Fault injection is test-mode only.'};[Console]::Out.WriteLine('artifact_retention_cleanup=READY action=before_commit');[Console]::Out.Flush();[Environment]::FailFast('Injected cleanup stop.')}
   Close-GeoraePlanArtifactRetentionHeldStageCleanupPlan $cleanupPlan;$cleanupPlan=$null
   $cleanupParent=Assert-GeoraePlanArtifactRetentionParent $AllowedParent;if($cleanupParent.Identity.VolumeSerialNumber-ine$cleanupParentBinding.VolumeSerialNumber-or$cleanupParent.Identity.FileId-ine$cleanupParentBinding.FileId-or$cleanupParent.MarkerSha256-ine$cleanupParentBinding.MarkerSha256-or$cleanupParent.BootstrapSha256-ine$cleanupParentBinding.BootstrapSha256){throw 'Artifact parent changed during cleanup postflight.'};$cleanupLease=Enter-GeoraePlanArtifactRetentionProducerLease $cleanupParent.LeasePath;Assert-GeoraePlanArtifactRetentionParentUnchanged $cleanupParent $cleanupParent.MarkerSha256 $cleanupLease
   $cleanupJournal=Open-GeoraePlanArtifactRetentionRelativeEntry $cleanupParent.Identity $finalizeName $false;if((Get-GeoraePlanArtifactRetentionSha256 (Read-GeoraePlanArtifactRetentionPinnedBytes $cleanupJournal))-ine$postPublication.JournalSha256){throw 'FinalizeJournal changed before stage cleanup commit.'}
   $cleanupFinal=Open-GeoraePlanArtifactRetentionRelativeEntry $cleanupParent.Identity $id $true;$cleanupOwner=Open-GeoraePlanArtifactRetentionRelativeEntry $cleanupFinal $script:GeoraePlanArtifactRetentionOwnerFileName $false;$cleanupManifest=Open-GeoraePlanArtifactRetentionRelativeEntry $cleanupFinal $script:GeoraePlanArtifactRetentionProducerManifestFileName $false;$cleanupCompletion=Open-GeoraePlanArtifactRetentionRelativeEntry $cleanupFinal $script:GeoraePlanArtifactRetentionCompletionFileName $false;$cleanupEvidence=Open-GeoraePlanArtifactRetentionStableFile ([string]$postPublication.Journal.evidencePath);$cleanupTree=Get-GeoraePlanArtifactRetentionHeldFinalConsumerTree $cleanupFinal @($postPublication.ExpectedEntries);if((Get-GeoraePlanArtifactRetentionSha256 (Read-GeoraePlanArtifactRetentionPinnedBytes $cleanupOwner)) -ine $postPublication.OwnerSha256 -or (Get-GeoraePlanArtifactRetentionSha256 (Read-GeoraePlanArtifactRetentionPinnedBytes $cleanupManifest)) -ine $postPublication.ManifestSha256 -or (Get-GeoraePlanArtifactRetentionSha256 (Read-GeoraePlanArtifactRetentionPinnedBytes $cleanupCompletion)) -ine $postPublication.CompletionSha256 -or (Get-GeoraePlanArtifactRetentionSha256 (Read-GeoraePlanArtifactRetentionPinnedBytes $cleanupEvidence)) -ine $postPublication.EvidenceSha256){throw 'Completed artifact metadata changed during stage cleanup postflight.'}
   $cleanupPlan=New-GeoraePlanArtifactRetentionHeldStageCleanupPlan $cleanupParent $cleanupLease $stageName $stageIdentity @($journal.materializationPlan) ([string]$journal.stageMarkerSha256) ([string]$journal.stageMarkerVolumeSerialNumber) ([string]$journal.stageMarkerFileId) -AllowMissing:$postPublication.Existing
   $freshFinalTree=$null;try{$freshFinalTree=Get-GeoraePlanArtifactRetentionHeldFinalConsumerTree $cleanupFinal @($postPublication.ExpectedEntries)}finally{Close-GeoraePlanArtifactRetentionHeldTree $freshFinalTree}
   Close-GeoraePlanArtifactRetentionHeldStageCleanupPlan $cleanupPlan -Commit -Fault $TestFaultInjection;$cleanupPlan=$null
   if(Test-Path -LiteralPath (Join-Path $cleanupParent.Path $stageName)){throw 'Stage cleanup did not remove the exact source stage.'}
   if($TestFaultInjection-eq'AddFinalChildAfterCommit'){if($env:GEORAEPLAN_ARTIFACT_PRODUCER_TEST_MODE-ne'1'){throw 'Fault injection is test-mode only.'};[IO.File]::WriteAllText((Join-Path $cleanupFinal.Path 'post-commit-test-child.txt'),'x',[Text.UTF8Encoding]::new($false))}
 }finally{if($null-ne$cleanupPlan){Close-GeoraePlanArtifactRetentionHeldStageCleanupPlan $cleanupPlan};Close-GeoraePlanArtifactRetentionHeldTree $cleanupTree;Close-GeoraePlanArtifactRetentionPinned $cleanupEvidence;Close-GeoraePlanArtifactRetentionPinned $cleanupCompletion;Close-GeoraePlanArtifactRetentionPinned $cleanupManifest;Close-GeoraePlanArtifactRetentionPinned $cleanupOwner;Close-GeoraePlanArtifactRetentionPinned $cleanupFinal;Close-GeoraePlanArtifactRetentionPinned $cleanupJournal;if($null -ne $cleanupLease){$cleanupLease.Dispose()};Close-GeoraePlanArtifactRetentionParent $cleanupParent}
 Invoke-GeoraePlanArtifactRetentionConsumerDryRun $id
 Write-Output "artifact_retention_completion=APPLIED action=completed artifact_id=$id commit_sha=$($postPublication.CommitSha)"
}
Close-GeoraePlanArtifactRetentionPinned $consumerSourceLease;Close-GeoraePlanArtifactRetentionPinned $powerShellToolLease;Close-GeoraePlanArtifactRetentionPinned $gitToolLease;Close-GeoraePlanArtifactRetentionPinned $dotnetToolLease
