$script:GeoraePlanArtifactRetentionParentOwnerFileName = '.georaeplan-retention-parent.json'
$script:GeoraePlanArtifactRetentionParentLeaseFileName = '.georaeplan-retention-parent.lease'
$script:GeoraePlanArtifactRetentionOwnerFileName = '.georaeplan-artifact-owner.json'
$script:GeoraePlanArtifactRetentionCompletionFileName = '.georaeplan-artifact-completion.json'
$script:GeoraePlanArtifactRetentionProducerManifestFileName = '.georaeplan-artifact-producer-manifest.json'
$script:GeoraePlanArtifactRetentionParentOwnerKind = 'georaeplan-artifact-retention-parent'
$script:GeoraePlanArtifactRetentionArtifactOwnerKind = 'georaeplan-private-guid-artifact'
$script:GeoraePlanArtifactRetentionParentEaName = 'GEORAEPLAN.RETENTION.PARENT'
$script:GeoraePlanArtifactRetentionStageEaName = 'GEORAEPLAN.RETENTION.STAGE'

function Initialize-GeoraePlanArtifactRetentionProducerNativeType {
    if ('GeoraePlan.ArtifactRetentionProducer.PinnedEntry' -as [type]) { return }
    Add-Type -TypeDefinition @'
using System;
using System.ComponentModel;
using System.IO;
using System.Collections.Generic;
using System.Runtime.InteropServices;
using Microsoft.Win32.SafeHandles;
namespace GeoraePlan.ArtifactRetentionProducer {
 public sealed class Identity { public string FinalPath; public string VolumeSerialNumber; public string FileId; public uint Links; public bool IsDirectory; public bool IsReparsePoint; }
 public sealed class ChildEntry { public string Name; public PinnedEntry Entry; }
 public sealed class PinnedEntry : IDisposable {
  const uint ReadAttributes=0x80, ReadEa=8, ListDirectory=1, Delete=0x00010000, GenericRead=0x80000000, GenericWrite=0x40000000, Synchronize=0x00100000, ShareRead=1, ShareWrite=2, OpenExisting=3, BackupSemantics=0x02000000, DirectoryAttribute=0x10, ReparsePoint=0x400;
  const uint ObjCaseInsensitive=0x40, FileOpen=1, FileCreate=2, FileDirectoryFile=1, FileNonDirectoryFile=0x40, FileSynchronousIoNonAlert=0x20, FileOpenReparsePoint=0x00200000;
  SafeFileHandle handle; public Identity EntryIdentity { get; private set; }
  PinnedEntry(SafeFileHandle h, Identity i) { handle=h; EntryIdentity=i; }
  public static PinnedEntry Open(string path) { return OpenCore(path,ShareRead|ShareWrite); }
  public static PinnedEntry OpenStableDirectory(string path) { return OpenCore(path,ShareRead); }
  public static PinnedEntry OpenStableFile(string path) { return OpenCore(path,ShareRead); }
  public static PinnedEntry OpenExclusiveFile(string path) { return OpenCore(path,0); }
  static PinnedEntry OpenCore(string path,uint share) { uint a=GetFileAttributes(path); if(a==0xffffffff) throw new Win32Exception(Marshal.GetLastWin32Error()); bool d=(a&DirectoryAttribute)!=0; var h=CreateFile(path,d?ReadAttributes|ReadEa|ListDirectory:GenericRead,share,IntPtr.Zero,OpenExisting,d?BackupSemantics:0,IntPtr.Zero); if(h.IsInvalid) throw new Win32Exception(Marshal.GetLastWin32Error()); try { return new PinnedEntry(h, Read(h,path,a,d)); } catch { h.Dispose(); throw; } }
  public PinnedEntry CreateRelativeDirectory(string name, string expectedPath, byte[] securityDescriptor) { return OpenRelative(name,expectedPath,securityDescriptor,true,null,true,null,null); }
  public PinnedEntry CreateProvisionedRelativeDirectory(string name,string expectedPath,byte[] securityDescriptor,string eaName,byte[] eaValue) { return OpenRelative(name,expectedPath,securityDescriptor,true,null,true,eaName,eaValue); }
  public PinnedEntry CreateRelativeFile(string name, string expectedPath, byte[] bytes, byte[] securityDescriptor) { return OpenRelative(name,expectedPath,securityDescriptor,false,bytes,true,null,null); }
  public PinnedEntry OpenRelativeEntry(string name,string expectedPath,bool directory) { return OpenRelative(name,expectedPath,null,directory,null,false,null,null); }
  public PinnedEntry OpenRelativeFileForRepair(string name,string expectedPath) { return OpenRelative(name,expectedPath,null,false,null,false,null,null,true); }
  public PinnedEntry OpenRelativeEntryForCleanup(string name,string expectedPath,bool directory) { return OpenRelative(name,expectedPath,null,directory,null,false,null,null,false,true); }
  PinnedEntry OpenRelative(string name,string expectedPath,byte[] securityDescriptor,bool directory,byte[] bytes,bool create,string eaName,byte[] eaValue,bool repair=false,bool cleanup=false) {
   if(String.IsNullOrEmpty(name)||name=="."||name==".."||name.IndexOf('\\')>=0||name.IndexOf('/')>=0) throw new ArgumentException("A relative leaf name is required.");
   IntPtr nameBuffer=IntPtr.Zero,unicodeBuffer=IntPtr.Zero,objectBuffer=IntPtr.Zero,sdBuffer=IntPtr.Zero,eaBuffer=IntPtr.Zero; int eaLength=0; SafeFileHandle created=null;
   try {
    byte[] encoded=System.Text.Encoding.Unicode.GetBytes(name); nameBuffer=Marshal.AllocHGlobal(encoded.Length); Marshal.Copy(encoded,0,nameBuffer,encoded.Length);
    UNICODE_STRING unicode=new UNICODE_STRING(); unicode.Length=(ushort)encoded.Length; unicode.MaximumLength=(ushort)encoded.Length; unicode.Buffer=nameBuffer;
    unicodeBuffer=Marshal.AllocHGlobal(Marshal.SizeOf(typeof(UNICODE_STRING))); Marshal.StructureToPtr(unicode,unicodeBuffer,false);
    OBJECT_ATTRIBUTES oa=new OBJECT_ATTRIBUTES(); oa.Length=(uint)Marshal.SizeOf(typeof(OBJECT_ATTRIBUTES)); oa.RootDirectory=handle.DangerousGetHandle(); oa.ObjectName=unicodeBuffer; oa.Attributes=ObjCaseInsensitive;
    if(securityDescriptor!=null){sdBuffer=Marshal.AllocHGlobal(securityDescriptor.Length);Marshal.Copy(securityDescriptor,0,sdBuffer,securityDescriptor.Length);oa.SecurityDescriptor=sdBuffer;}
    if(eaName!=null||eaValue!=null){if(!create||String.IsNullOrWhiteSpace(eaName)||eaValue==null||eaValue.Length==0)throw new IOException("Relative create EA is invalid.");byte[] ea=BuildEaBuffer(eaName,eaValue);eaLength=ea.Length;eaBuffer=Marshal.AllocHGlobal(eaLength);Marshal.Copy(ea,0,eaBuffer,eaLength);}
    objectBuffer=Marshal.AllocHGlobal(Marshal.SizeOf(typeof(OBJECT_ATTRIBUTES))); Marshal.StructureToPtr(oa,objectBuffer,false);
     IO_STATUS_BLOCK io; uint access=Synchronize|ReadAttributes|(directory?(ListDirectory|ReadEa):(GenericRead|((create||repair)?GenericWrite:0)))|(cleanup?Delete:0); uint options=FileSynchronousIoNonAlert|FileOpenReparsePoint|(directory?FileDirectoryFile:FileNonDirectoryFile);
     int status=NtCreateFile(out created,access,objectBuffer,out io,IntPtr.Zero,0,repair?0:ShareRead,create?FileCreate:FileOpen,options,eaBuffer,(uint)eaLength);
    if(status<0) throw new Win32Exception((int)RtlNtStatusToDosError(status));
    if(!directory&&bytes!=null){uint written=0;if(bytes.Length>0&&!WriteFile(created,bytes,(uint)bytes.Length,out written,IntPtr.Zero))throw new Win32Exception(Marshal.GetLastWin32Error());if(written!=bytes.Length)throw new System.IO.IOException("Short metadata write.");if(!FlushFileBuffers(created))throw new Win32Exception(Marshal.GetLastWin32Error());}
    uint attrs=GetFileAttributes(expectedPath); if(attrs==0xffffffff)throw new Win32Exception(Marshal.GetLastWin32Error()); var result=new PinnedEntry(created,Read(created,expectedPath,attrs,directory)); created=null; return result;
   } finally { if(created!=null)created.Dispose();if(eaBuffer!=IntPtr.Zero)Marshal.FreeHGlobal(eaBuffer); if(objectBuffer!=IntPtr.Zero)Marshal.FreeHGlobal(objectBuffer);if(sdBuffer!=IntPtr.Zero)Marshal.FreeHGlobal(sdBuffer);if(unicodeBuffer!=IntPtr.Zero)Marshal.FreeHGlobal(unicodeBuffer);if(nameBuffer!=IntPtr.Zero)Marshal.FreeHGlobal(nameBuffer); }
  }
  static byte[] BuildEaBuffer(string name,byte[] value){byte[] n=System.Text.Encoding.ASCII.GetBytes(name);if(n.Length==0||n.Length>255||value.Length>65535)throw new IOException("Provisioning EA is outside bounds.");foreach(byte b in n)if(b<0x21||b>0x7e||b==(byte)'=')throw new IOException("Provisioning EA name is invalid.");byte[] x=new byte[8+n.Length+1+value.Length];x[5]=(byte)n.Length;x[6]=(byte)(value.Length&255);x[7]=(byte)((value.Length>>8)&255);Buffer.BlockCopy(n,0,x,8,n.Length);Buffer.BlockCopy(value,0,x,9+n.Length,value.Length);return x;}
  public byte[] ReadExtendedAttribute(string name){byte[] n=System.Text.Encoding.ASCII.GetBytes(name);IntPtr p=Marshal.AllocHGlobal(65536);try{IO_STATUS_BLOCK io;int status=NtQueryEaFile(handle,out io,p,65536,false,IntPtr.Zero,0,IntPtr.Zero,true);if(status!=0)throw new IOException("Provisioning EA cannot be read. NTSTATUS=0x"+status.ToString("X8"));int nl=Marshal.ReadByte(p,5),vl=(ushort)Marshal.ReadInt16(p,6);if(Marshal.ReadInt32(p,0)!=0||nl!=n.Length||vl<=0)throw new IOException("Provisioning EA is nonconforming.");byte[] actual=new byte[nl];Marshal.Copy(IntPtr.Add(p,8),actual,0,nl);for(int i=0;i<nl;i++)if(actual[i]!=n[i])throw new IOException("Provisioning EA name changed.");byte[] value=new byte[vl];Marshal.Copy(IntPtr.Add(p,9+nl),value,0,vl);return value;}finally{Marshal.FreeHGlobal(p);}}
  public byte[] ReadAllBytes() { if(EntryIdentity.IsDirectory) throw new InvalidOperationException("Directory bytes cannot be read."); SafeFileHandle duplicate; if(!DuplicateHandle(GetCurrentProcess(),handle,GetCurrentProcess(),out duplicate,0,false,2)) throw new Win32Exception(Marshal.GetLastWin32Error()); try { using(var stream=new System.IO.FileStream(duplicate,System.IO.FileAccess.Read)){duplicate=null;stream.Position=0;using(var memory=new System.IO.MemoryStream()){stream.CopyTo(memory);return memory.ToArray();}} } finally {if(duplicate!=null)duplicate.Dispose();} }
  public void CompleteExpectedBytes(byte[] expected) { byte[] actual=ReadAllBytes();if(actual.Length>expected.Length)throw new IOException("Pending metadata is longer than expected.");for(int i=0;i<actual.Length;i++)if(actual[i]!=expected[i])throw new IOException("Pending metadata is not an exact expected prefix.");long position;if(!SetFilePointerEx(handle,actual.Length,out position,0)||position!=actual.Length)throw new Win32Exception(Marshal.GetLastWin32Error());if(actual.Length<expected.Length){byte[] remaining=new byte[expected.Length-actual.Length];Buffer.BlockCopy(expected,actual.Length,remaining,0,remaining.Length);uint written;if(!WriteFile(handle,remaining,(uint)remaining.Length,out written,IntPtr.Zero)||written!=remaining.Length)throw new IOException("Pending metadata completion write failed.");}if(!FlushFileBuffers(handle))throw new Win32Exception(Marshal.GetLastWin32Error());byte[] complete=ReadAllBytes();if(complete.Length!=expected.Length)throw new IOException("Pending metadata completion length is invalid.");for(int i=0;i<complete.Length;i++)if(complete[i]!=expected[i])throw new IOException("Pending metadata completion bytes are invalid."); }
  public void MarkDelete() { SetDeleteDisposition(true); }
  public void ClearDelete() { SetDeleteDisposition(false); }
  void SetDeleteDisposition(bool delete) { IO_STATUS_BLOCK io; FILE_DISPOSITION_INFORMATION disposition=new FILE_DISPOSITION_INFORMATION();disposition.DeleteFile=delete;int status=NtSetInformationFile(handle,out io,ref disposition,(uint)Marshal.SizeOf(typeof(FILE_DISPOSITION_INFORMATION)),13);if(status<0)throw new IOException("Held entry delete disposition failed. NTSTATUS=0x"+status.ToString("X8")); }
  public ChildEntry[] EnumerateAndOpenChildren(string expectedDirectoryPath,string phase) { return EnumerateAndOpenChildrenCore(expectedDirectoryPath,null,null,phase,false); }
  public ChildEntry[] EnumerateAndOpenChildrenForCleanup(string expectedDirectoryPath) { return EnumerateAndOpenChildrenCore(expectedDirectoryPath,null,null,"cleanup",true); }
  public ChildEntry[] EnumerateAndOpenChildrenExceptHeld(string expectedDirectoryPath,string heldLeafName,PinnedEntry heldFile,string phase) { if(String.IsNullOrEmpty(heldLeafName)||heldLeafName.IndexOfAny(new[]{'\\','/'})>=0||heldFile==null||heldFile.EntryIdentity.IsDirectory||heldFile.EntryIdentity.IsReparsePoint||heldFile.EntryIdentity.Links!=1)throw new ArgumentException("Held leaf identity is invalid.");return EnumerateAndOpenChildrenCore(expectedDirectoryPath,heldLeafName,Convert.ToUInt64(heldFile.EntryIdentity.FileId,16),phase,false); }
  ChildEntry[] EnumerateAndOpenChildrenCore(string expectedDirectoryPath,string heldLeafName,ulong? heldFileId,string phase,bool cleanup) { if(!EntryIdentity.IsDirectory)throw new InvalidOperationException("Directory handle required.");if(phase!="parent"&&phase!="source"&&phase!="final-subset"&&phase!="cleanup")throw new ArgumentException("Enumeration phase is invalid.");var children=new List<ChildEntry>();IntPtr buffer=Marshal.AllocHGlobal(65536);bool restart=true;try{while(true){IO_STATUS_BLOCK io;int status=NtQueryDirectoryFile(handle,IntPtr.Zero,IntPtr.Zero,IntPtr.Zero,out io,buffer,65536,37,true,IntPtr.Zero,restart);restart=false;if(status==unchecked((int)0x80000006))break;if(status<0)throw new IOException("Held directory enumeration failed. phase="+phase+" NTSTATUS=0x"+status.ToString("X8"));int nameLength=Marshal.ReadInt32(buffer,60);string name=Marshal.PtrToStringUni(IntPtr.Add(buffer,104),nameLength/2);if(name=="."||name=="..")continue;uint attributes=(uint)Marshal.ReadInt32(buffer,56);bool directory=(attributes&DirectoryAttribute)!=0;ulong enumeratedId=(ulong)Marshal.ReadInt64(buffer,96);if(String.Equals(name,heldLeafName,StringComparison.Ordinal)){if(!heldFileId.HasValue||directory||enumeratedId!=heldFileId.Value)throw new IOException("Held coordinator enumeration identity is invalid.");children.Add(new ChildEntry{Name=name,Entry=null});continue;}PinnedEntry child=null;try{try{child=OpenRelative(name,System.IO.Path.Combine(expectedDirectoryPath,name),null,directory,null,false,null,null,false,cleanup);}catch(Win32Exception ex){throw new IOException("Held relative open failed. phase="+phase+" entry_kind="+(directory?"directory":"file")+" win32="+ex.NativeErrorCode,ex);}ulong openedId=Convert.ToUInt64(child.EntryIdentity.FileId,16);if(openedId!=enumeratedId)throw new IOException("Enumerated child identity changed before relative open. phase="+phase+" entry_kind="+(directory?"directory":"file"));children.Add(new ChildEntry{Name=name,Entry=child});child=null;}finally{if(child!=null)child.Dispose();}}return children.ToArray();}catch{foreach(var child in children)if(child.Entry!=null)child.Entry.Dispose();throw;}finally{Marshal.FreeHGlobal(buffer);} }
  public void Validate(string path) { var i=Read(handle,path,GetFileAttributes(path),EntryIdentity.IsDirectory); if(!String.Equals(i.FinalPath,path,StringComparison.OrdinalIgnoreCase)||i.VolumeSerialNumber!=EntryIdentity.VolumeSerialNumber||i.FileId!=EntryIdentity.FileId||i.Links!=EntryIdentity.Links||i.IsReparsePoint) throw new InvalidOperationException("Pinned filesystem entry changed."); }
  static Identity Read(SafeFileHandle h,string expected,uint attrs,bool directory) { BY_HANDLE_FILE_INFORMATION x; if(!GetFileInformationByHandle(h,out x)) throw new Win32Exception(Marshal.GetLastWin32Error()); char[] b=new char[32768]; uint n=GetFinalPathNameByHandle(h,b,(uint)b.Length,0); if(n==0||n>=b.Length) throw new Win32Exception(Marshal.GetLastWin32Error()); string p=new String(b,0,(int)n); if(p.StartsWith(@"\\?\UNC\",StringComparison.OrdinalIgnoreCase)) p=@"\\"+p.Substring(8); else if(p.StartsWith(@"\\?\",StringComparison.OrdinalIgnoreCase)) p=p.Substring(4); ulong id=((ulong)x.FileIndexHigh<<32)|x.FileIndexLow; return new Identity { FinalPath=p, VolumeSerialNumber=x.VolumeSerialNumber.ToString("X8"), FileId=id.ToString("X16"), Links=x.NumberOfLinks, IsDirectory=directory, IsReparsePoint=(x.FileAttributes&ReparsePoint)!=0}; }
  public void Dispose(){ if(handle!=null) handle.Dispose(); }
  [StructLayout(LayoutKind.Sequential)] struct FILETIME { public uint a,b; }
  [StructLayout(LayoutKind.Sequential)] struct BY_HANDLE_FILE_INFORMATION { public uint FileAttributes; public FILETIME CreationTime,LastAccessTime,LastWriteTime; public uint VolumeSerialNumber,FileSizeHigh,FileSizeLow,NumberOfLinks,FileIndexHigh,FileIndexLow; }
  [StructLayout(LayoutKind.Sequential)] struct UNICODE_STRING { public ushort Length,MaximumLength; public IntPtr Buffer; }
  [StructLayout(LayoutKind.Sequential)] struct OBJECT_ATTRIBUTES { public uint Length; public IntPtr RootDirectory,ObjectName; public uint Attributes; public IntPtr SecurityDescriptor,SecurityQualityOfService; }
  [StructLayout(LayoutKind.Sequential)] struct IO_STATUS_BLOCK { public IntPtr Status; public UIntPtr Information; }
  [StructLayout(LayoutKind.Sequential)] struct FILE_DISPOSITION_INFORMATION { [MarshalAs(UnmanagedType.I1)] public bool DeleteFile; }
  [DllImport("kernel32.dll",CharSet=CharSet.Unicode,SetLastError=true)] static extern SafeFileHandle CreateFile(string n,uint a,uint s,IntPtr q,uint c,uint f,IntPtr t);
  [DllImport("kernel32.dll",CharSet=CharSet.Unicode,SetLastError=true)] static extern uint GetFinalPathNameByHandle(SafeFileHandle h,[Out]char[] b,uint n,uint f);
  [DllImport("kernel32.dll",SetLastError=true)] static extern bool GetFileInformationByHandle(SafeFileHandle h,out BY_HANDLE_FILE_INFORMATION x);
  [DllImport("kernel32.dll",SetLastError=true)] static extern bool WriteFile(SafeFileHandle h,byte[] b,uint n,out uint w,IntPtr o);
  [DllImport("kernel32.dll",SetLastError=true)] static extern bool FlushFileBuffers(SafeFileHandle h);
  [DllImport("kernel32.dll",SetLastError=true)] static extern bool SetFilePointerEx(SafeFileHandle h,long distance,out long position,uint method);
  [DllImport("kernel32.dll")] static extern IntPtr GetCurrentProcess();
  [DllImport("kernel32.dll",SetLastError=true)] static extern bool DuplicateHandle(IntPtr sourceProcess,SafeFileHandle source,IntPtr targetProcess,out SafeFileHandle target,uint desiredAccess,bool inherit,uint options);
  [DllImport("kernel32.dll",CharSet=CharSet.Unicode,SetLastError=true)] static extern uint GetFileAttributes(string n);
  [DllImport("ntdll.dll")] static extern int NtCreateFile(out SafeFileHandle h,uint a,IntPtr o,out IO_STATUS_BLOCK i,IntPtr s,uint f,uint sh,uint d,uint opt,IntPtr e,uint l);
  [DllImport("ntdll.dll")] static extern int NtQueryEaFile(SafeFileHandle h,out IO_STATUS_BLOCK i,IntPtr b,uint l,bool single,IntPtr list,uint listLength,IntPtr index,bool restart);
  [DllImport("ntdll.dll")] static extern int NtQueryDirectoryFile(SafeFileHandle h,IntPtr e,IntPtr apc,IntPtr context,out IO_STATUS_BLOCK i,IntPtr b,uint l,int informationClass,bool single,IntPtr name,bool restart);
  [DllImport("ntdll.dll")] static extern int NtSetInformationFile(SafeFileHandle h,out IO_STATUS_BLOCK i,ref FILE_DISPOSITION_INFORMATION b,uint l,int informationClass);
  [DllImport("ntdll.dll")] static extern uint RtlNtStatusToDosError(int status);
 }
}
'@
}

function Get-GeoraePlanArtifactRetentionNormalizedPath { param([Parameter(Mandatory=$true)][string]$Path) $p=[IO.Path]::GetFullPath($Path); if($p.Length -gt 3){$p=$p.TrimEnd('\')}; return $p }
function Test-GeoraePlanArtifactRetentionPathEquals { param([string]$Left,[string]$Right) return [string]::Equals((Get-GeoraePlanArtifactRetentionNormalizedPath $Left),(Get-GeoraePlanArtifactRetentionNormalizedPath $Right),[StringComparison]::OrdinalIgnoreCase) }
function Test-GeoraePlanArtifactRetentionPathInside { param([string]$Parent,[string]$Candidate) $p=(Get-GeoraePlanArtifactRetentionNormalizedPath $Parent)+'\'; return (Get-GeoraePlanArtifactRetentionNormalizedPath $Candidate).StartsWith($p,[StringComparison]::OrdinalIgnoreCase) }

function Open-GeoraePlanArtifactRetentionPinned { param([Parameter(Mandatory=$true)][string]$Path,[switch]$StableDirectory) Initialize-GeoraePlanArtifactRetentionProducerNativeType; $full=Get-GeoraePlanArtifactRetentionNormalizedPath $Path; if($StableDirectory){$entry=[GeoraePlan.ArtifactRetentionProducer.PinnedEntry]::OpenStableDirectory($full)}else{$entry=[GeoraePlan.ArtifactRetentionProducer.PinnedEntry]::Open($full)}; try { $i=$entry.EntryIdentity; if($i.IsReparsePoint -or (-not $i.IsDirectory -and $i.Links -ne 1) -or -not (Test-GeoraePlanArtifactRetentionPathEquals $i.FinalPath $full)){ throw 'Pinned artifact entry has an unsafe physical identity.' }; return [pscustomobject]@{ Path=$full; PhysicalPath=(Get-GeoraePlanArtifactRetentionNormalizedPath $i.FinalPath); VolumeSerialNumber=$i.VolumeSerialNumber; FileId=$i.FileId; NumberOfLinks=[uint32]$i.Links; IsDirectory=[bool]$i.IsDirectory; NativeHandle=$entry } } catch { $entry.Dispose(); throw } }
function Open-GeoraePlanArtifactRetentionStableFile { param([Parameter(Mandatory=$true)][string]$Path) Initialize-GeoraePlanArtifactRetentionProducerNativeType;$full=Get-GeoraePlanArtifactRetentionNormalizedPath $Path;$entry=[GeoraePlan.ArtifactRetentionProducer.PinnedEntry]::OpenStableFile($full);try{$i=$entry.EntryIdentity;if($i.IsDirectory -or $i.IsReparsePoint -or $i.Links -ne 1 -or -not(Test-GeoraePlanArtifactRetentionPathEquals $i.FinalPath $full)){throw 'Stable artifact file has an unsafe physical identity.'};return [pscustomobject]@{Path=$full;PhysicalPath=(Get-GeoraePlanArtifactRetentionNormalizedPath $i.FinalPath);VolumeSerialNumber=$i.VolumeSerialNumber;FileId=$i.FileId;NumberOfLinks=[uint32]$i.Links;IsDirectory=$false;NativeHandle=$entry}}catch{$entry.Dispose();throw} }
# Stable file and directory handles never grant delete sharing.
function Assert-GeoraePlanArtifactRetentionPinned { param([Parameter(Mandatory=$true)]$Pinned) $Pinned.NativeHandle.Validate($Pinned.Path); return $Pinned }
function Close-GeoraePlanArtifactRetentionPinned { param($Pinned) if($null -ne $Pinned -and $null -ne $Pinned.NativeHandle){$Pinned.NativeHandle.Dispose()} }
function Get-GeoraePlanArtifactRetentionIdentity { param([string]$Path,[switch]$Exclusive) $p=Open-GeoraePlanArtifactRetentionPinned $Path; try { return [pscustomobject]@{Path=$p.Path;PhysicalPath=$p.PhysicalPath;VolumeSerialNumber=$p.VolumeSerialNumber;FileId=$p.FileId;NumberOfLinks=$p.NumberOfLinks;IsDirectory=$p.IsDirectory} } finally { Close-GeoraePlanArtifactRetentionPinned $p } }

function Get-GeoraePlanArtifactRetentionAllowedSids { return @([Security.Principal.WindowsIdentity]::GetCurrent().User.Value,'S-1-5-18','S-1-5-32-544' | Select-Object -Unique) }
function Get-GeoraePlanArtifactRetentionPrivateAcl { $owner=[Security.Principal.WindowsIdentity]::GetCurrent().User;$acl=New-Object Security.AccessControl.DirectorySecurity;$acl.SetOwner($owner);$acl.SetAccessRuleProtection($true,$false);$inherit=[Security.AccessControl.InheritanceFlags]::ContainerInherit -bor [Security.AccessControl.InheritanceFlags]::ObjectInherit;foreach($sidText in Get-GeoraePlanArtifactRetentionAllowedSids){[void]$acl.AddAccessRule((New-Object Security.AccessControl.FileSystemAccessRule([Security.Principal.SecurityIdentifier]$sidText,[Security.AccessControl.FileSystemRights]::FullControl,$inherit,[Security.AccessControl.PropagationFlags]::None,[Security.AccessControl.AccessControlType]::Allow)))};return $acl }
function Get-GeoraePlanArtifactRetentionPrivateAclBytes { $acl=Get-GeoraePlanArtifactRetentionPrivateAcl;$bytes=$acl.GetSecurityDescriptorBinaryForm();return ,$bytes }
function Get-GeoraePlanArtifactRetentionPrivateFileAcl { $owner=[Security.Principal.WindowsIdentity]::GetCurrent().User;$acl=New-Object Security.AccessControl.FileSecurity;$acl.SetOwner($owner);$acl.SetAccessRuleProtection($true,$false);foreach($sidText in Get-GeoraePlanArtifactRetentionAllowedSids){[void]$acl.AddAccessRule((New-Object Security.AccessControl.FileSystemAccessRule([Security.Principal.SecurityIdentifier]$sidText,[Security.AccessControl.FileSystemRights]::FullControl,[Security.AccessControl.AccessControlType]::Allow)))};return $acl }
function Get-GeoraePlanArtifactRetentionPrivateFileAclBytes { $acl=Get-GeoraePlanArtifactRetentionPrivateFileAcl;return ,$acl.GetSecurityDescriptorBinaryForm() }
function Set-GeoraePlanArtifactRetentionPrivateAcl { param([string]$Path) $acl=Get-GeoraePlanArtifactRetentionPrivateAcl;Set-Acl -LiteralPath $Path -AclObject $acl -ErrorAction Stop;Assert-GeoraePlanArtifactRetentionPrivateAcl $Path }
function Assert-GeoraePlanArtifactRetentionPrivateAcl { param([string]$Path) $acl=Get-Acl -LiteralPath $Path -ErrorAction Stop; $current=[Security.Principal.WindowsIdentity]::GetCurrent().User.Value; $owner=$acl.GetOwner([Security.Principal.SecurityIdentifier]).Value; if($owner -cne $current -or -not $acl.AreAccessRulesProtected){throw 'Private artifact ACL owner/protection is invalid.'}; $expected=@(Get-GeoraePlanArtifactRetentionAllowedSids | Sort-Object); $actual=New-Object Collections.Generic.List[string]; foreach($rule in @($acl.Access)){ if($rule.IsInherited -or $rule.AccessControlType -ne [Security.AccessControl.AccessControlType]::Allow -or $rule.FileSystemRights -ne [Security.AccessControl.FileSystemRights]::FullControl){throw 'Private artifact ACL has an inherited, deny, or non-full-control entry.'}; $sid=$rule.IdentityReference.Translate([Security.Principal.SecurityIdentifier]).Value; $actual.Add($sid) }; $actual=@($actual | Sort-Object); if($actual.Count -ne $expected.Count -or (@(Compare-Object $actual $expected).Count -ne 0)){throw 'Private artifact ACL allowlist is not exact.'} }
function Assert-GeoraePlanArtifactRetentionPrivateFileAcl { param([string]$Path) $acl=Get-Acl -LiteralPath $Path -ErrorAction Stop;$current=[Security.Principal.WindowsIdentity]::GetCurrent().User.Value;$owner=$acl.GetOwner([Security.Principal.SecurityIdentifier]).Value;if($owner -cne $current -or -not $acl.AreAccessRulesProtected){throw 'Private artifact file ACL owner/protection is invalid.'};$expected=@(Get-GeoraePlanArtifactRetentionAllowedSids|Sort-Object);$actual=New-Object Collections.Generic.List[string];foreach($rule in @($acl.Access)){if($rule.IsInherited -or $rule.AccessControlType -ne [Security.AccessControl.AccessControlType]::Allow -or $rule.FileSystemRights -ne [Security.AccessControl.FileSystemRights]::FullControl -or $rule.InheritanceFlags -ne [Security.AccessControl.InheritanceFlags]::None){throw 'Private artifact file ACL is not exact.'};$actual.Add($rule.IdentityReference.Translate([Security.Principal.SecurityIdentifier]).Value)};$actual=@($actual|Sort-Object);if($actual.Count -ne $expected.Count -or @(Compare-Object $actual $expected).Count -ne 0){throw 'Private artifact file ACL allowlist is not exact.'} }

function ConvertTo-GeoraePlanArtifactRetentionStrictJson { param($Value) return ($Value | ConvertTo-Json -Depth 20 -Compress) }
function New-GeoraePlanArtifactRetentionRelativeDirectory { param($Parent,[string]$Name) $path=Join-Path $Parent.Path $Name;$native=$Parent.NativeHandle.CreateRelativeDirectory($Name,$path,(Get-GeoraePlanArtifactRetentionPrivateAclBytes));try{$i=$native.EntryIdentity;return [pscustomobject]@{Path=$path;PhysicalPath=(Get-GeoraePlanArtifactRetentionNormalizedPath $i.FinalPath);VolumeSerialNumber=$i.VolumeSerialNumber;FileId=$i.FileId;NumberOfLinks=[uint32]$i.Links;IsDirectory=$true;NativeHandle=$native}}catch{$native.Dispose();throw} }
function New-GeoraePlanArtifactRetentionProvisionedRelativeDirectory { param($Parent,[string]$Name,[string]$EaName,[byte[]]$TokenBytes) $path=Join-Path $Parent.Path $Name;$native=$Parent.NativeHandle.CreateProvisionedRelativeDirectory($Name,$path,(Get-GeoraePlanArtifactRetentionPrivateAclBytes),$EaName,$TokenBytes);try{$i=$native.EntryIdentity;return [pscustomobject]@{Path=$path;PhysicalPath=(Get-GeoraePlanArtifactRetentionNormalizedPath $i.FinalPath);VolumeSerialNumber=$i.VolumeSerialNumber;FileId=$i.FileId;NumberOfLinks=[uint32]$i.Links;IsDirectory=$true;NativeHandle=$native}}catch{$native.Dispose();throw} }
function Assert-GeoraePlanArtifactRetentionProvisioningToken { param($PinnedDirectory,[string]$EaName,[byte[]]$ExpectedBytes) Assert-GeoraePlanArtifactRetentionPinned $PinnedDirectory|Out-Null;$actual=$PinnedDirectory.NativeHandle.ReadExtendedAttribute($EaName);if($actual.Length -ne $ExpectedBytes.Length){throw 'Provisioning token length changed.'};$difference=0;for($i=0;$i -lt $actual.Length;$i++){$difference=$difference -bor ($actual[$i] -bxor $ExpectedBytes[$i])};if($difference -ne 0){throw 'Provisioning token changed.'};return $actual }
function Open-GeoraePlanArtifactRetentionRelativeEntry { param($Parent,[string]$Name,[bool]$IsDirectory) if([string]::IsNullOrWhiteSpace($Name) -or $Name -in @('.','..') -or $Name.Contains('\') -or $Name.Contains('/')){throw 'Relative artifact entry name is unsafe.'};$path=Join-Path $Parent.Path $Name;$native=$Parent.NativeHandle.OpenRelativeEntry($Name,$path,$IsDirectory);try{$i=$native.EntryIdentity;if($i.IsReparsePoint -or $i.IsDirectory -ne $IsDirectory -or (-not $IsDirectory -and $i.Links -ne 1) -or -not(Test-GeoraePlanArtifactRetentionPathEquals $i.FinalPath $path)){throw 'Relative artifact entry physical identity is unsafe.'};return [pscustomobject]@{Path=$path;PhysicalPath=(Get-GeoraePlanArtifactRetentionNormalizedPath $i.FinalPath);VolumeSerialNumber=$i.VolumeSerialNumber;FileId=$i.FileId;NumberOfLinks=[uint32]$i.Links;IsDirectory=[bool]$i.IsDirectory;NativeHandle=$native}}catch{$native.Dispose();throw} }
function Open-GeoraePlanArtifactRetentionRelativeEntryForCleanup { param($Parent,[string]$Name,[bool]$IsDirectory) if([string]::IsNullOrWhiteSpace($Name) -or $Name -in @('.','..') -or $Name.Contains('\') -or $Name.Contains('/')){throw 'Cleanup entry name is unsafe.'};$path=Join-Path $Parent.Path $Name;$native=$Parent.NativeHandle.OpenRelativeEntryForCleanup($Name,$path,$IsDirectory);try{$i=$native.EntryIdentity;if($i.IsReparsePoint -or $i.IsDirectory -ne $IsDirectory -or (-not$IsDirectory -and $i.Links -ne 1) -or -not(Test-GeoraePlanArtifactRetentionPathEquals $i.FinalPath $path)){throw 'Cleanup entry physical identity is unsafe.'};return [pscustomobject]@{Path=$path;PhysicalPath=(Get-GeoraePlanArtifactRetentionNormalizedPath $i.FinalPath);VolumeSerialNumber=$i.VolumeSerialNumber;FileId=$i.FileId;NumberOfLinks=[uint32]$i.Links;IsDirectory=[bool]$i.IsDirectory;NativeHandle=$native}}catch{$native.Dispose();throw} }
function ConvertFrom-GeoraePlanArtifactRetentionNativeChild { param($Parent,$Record) $path=Join-Path $Parent.Path $Record.Name;$native=$Record.Entry;try{$i=$native.EntryIdentity;if($i.IsReparsePoint -or (-not$i.IsDirectory -and $i.Links -ne 1) -or -not(Test-GeoraePlanArtifactRetentionPathEquals $i.FinalPath $path)){throw 'Enumerated artifact child physical identity is unsafe.'};return [pscustomobject]@{Path=$path;PhysicalPath=(Get-GeoraePlanArtifactRetentionNormalizedPath $i.FinalPath);VolumeSerialNumber=$i.VolumeSerialNumber;FileId=$i.FileId;NumberOfLinks=[uint32]$i.Links;IsDirectory=[bool]$i.IsDirectory;NativeHandle=$native}}catch{$native.Dispose();throw} }
function Read-GeoraePlanArtifactRetentionPinnedBytes { param($PinnedFile) Assert-GeoraePlanArtifactRetentionPinned $PinnedFile|Out-Null;$bytes=$PinnedFile.NativeHandle.ReadAllBytes();Assert-GeoraePlanArtifactRetentionPinned $PinnedFile|Out-Null;return ,$bytes }
function Write-GeoraePlanArtifactRetentionRelativeCreateNewBytes {
 param($Parent,[string]$Name,[byte[]]$Bytes,[int]$TestPartialLength=-1)
 if([string]::IsNullOrWhiteSpace($Name) -or $Name.Contains('\') -or $Name.Contains('/')){throw 'Durable metadata destination name is invalid.'}
 $path=Join-Path $Parent.Path $Name;$writer=$null;$stable=$null
 try{
  if(Test-Path -LiteralPath $path){$writer=$Parent.NativeHandle.OpenRelativeFileForRepair($Name,$path);Assert-GeoraePlanArtifactRetentionPrivateFileAcl $path}
  else{
   $publishedBytes=$Bytes
   if($TestPartialLength -ge 0){if($env:GEORAEPLAN_ARTIFACT_PRODUCER_TEST_MODE -ne '1' -or $TestPartialLength -ge $Bytes.Length){throw 'Partial metadata fault injection is invalid.'};$publishedBytes=New-Object byte[] $TestPartialLength;if($TestPartialLength -gt 0){[Array]::Copy($Bytes,$publishedBytes,$TestPartialLength)}}
   $writer=$Parent.NativeHandle.CreateRelativeFile($Name,$path,$publishedBytes,(Get-GeoraePlanArtifactRetentionPrivateFileAclBytes));Assert-GeoraePlanArtifactRetentionPrivateFileAcl $path
   if($TestPartialLength -ge 0){throw 'Injected partial durable metadata publication.'}
  }
  $created=$writer.EntryIdentity;if($created.IsDirectory -or $created.IsReparsePoint -or $created.Links -ne 1 -or -not(Test-GeoraePlanArtifactRetentionPathEquals $created.FinalPath $path)){throw 'Durable metadata identity is invalid.'}
  $writer.CompleteExpectedBytes($Bytes);$writer.Dispose();$writer=$null
  Assert-GeoraePlanArtifactRetentionPrivateFileAcl $path
  $stable=$Parent.NativeHandle.OpenRelativeEntry($Name,$path,$false);$actual=$stable.EntryIdentity
  if($actual.IsDirectory -or $actual.IsReparsePoint -or $actual.Links -ne 1 -or $actual.VolumeSerialNumber -ine $created.VolumeSerialNumber -or $actual.FileId -ine $created.FileId -or -not(Test-GeoraePlanArtifactRetentionPathEquals $actual.FinalPath $path)){throw 'Published metadata identity changed before stable reopen.'}
  $stable.Validate($path);$read=$stable.ReadAllBytes();if($read.Length -ne $Bytes.Length -or (Get-GeoraePlanArtifactRetentionSha256 $read) -cne (Get-GeoraePlanArtifactRetentionSha256 $Bytes)){throw 'Published metadata bytes changed before stable reopen.'}
  $result=[pscustomobject]@{Path=$path;PhysicalPath=(Get-GeoraePlanArtifactRetentionNormalizedPath $actual.FinalPath);VolumeSerialNumber=$actual.VolumeSerialNumber;FileId=$actual.FileId;NumberOfLinks=[uint32]$actual.Links;IsDirectory=$false;NativeHandle=$stable};$stable=$null;return $result
 }finally{if($null -ne $writer){$writer.Dispose()};if($null -ne $stable){$stable.Dispose()}}
}
function Write-GeoraePlanArtifactRetentionRelativeCreateNewJson { param($Parent,[string]$Name,$Value) $bytes=[Text.UTF8Encoding]::new($false).GetBytes((ConvertTo-GeoraePlanArtifactRetentionStrictJson $Value));$created=Write-GeoraePlanArtifactRetentionRelativeCreateNewBytes $Parent $Name $bytes;try{return (Get-GeoraePlanArtifactRetentionSha256 $bytes)}finally{Close-GeoraePlanArtifactRetentionPinned $created} }
function Write-GeoraePlanArtifactRetentionCreateNewJson { param([string]$Path,$Value) $destination=Get-GeoraePlanArtifactRetentionNormalizedPath $Path;$parent=Open-GeoraePlanArtifactRetentionPinned (Split-Path -Parent $destination);try{return Write-GeoraePlanArtifactRetentionRelativeCreateNewJson $parent (Split-Path -Leaf $destination) $Value}finally{Close-GeoraePlanArtifactRetentionPinned $parent} }
function Read-GeoraePlanArtifactRetentionStrictJson { param([string]$Path,[string]$Label) $pin=Open-GeoraePlanArtifactRetentionStableFile $Path; try{$reader=New-Object IO.StreamReader((New-Object IO.FileStream($pin.Path,[IO.FileMode]::Open,[IO.FileAccess]::Read,[IO.FileShare]::Read)),[Text.UTF8Encoding]::new($false),$true);try{$raw=$reader.ReadToEnd()}finally{$reader.Dispose()};Assert-GeoraePlanArtifactRetentionPinned $pin|Out-Null;if([string]::IsNullOrWhiteSpace($raw)){throw "$Label must be canonical JSON."};$value=$raw|ConvertFrom-Json -ErrorAction Stop;$canonical=ConvertTo-GeoraePlanArtifactRetentionStrictJson $value;if($raw -cne $canonical){throw "$Label must be canonical JSON."};return $value}finally{Close-GeoraePlanArtifactRetentionPinned $pin} }
function Read-GeoraePlanArtifactRetentionPinnedStrictJson { param($PinnedFile,[string]$Label) $bytes=Read-GeoraePlanArtifactRetentionPinnedBytes $PinnedFile;$raw=[Text.UTF8Encoding]::new($false,$true).GetString($bytes);if([string]::IsNullOrWhiteSpace($raw)){throw "$Label must be canonical JSON."};$value=$raw|ConvertFrom-Json -ErrorAction Stop;if($raw -cne (ConvertTo-GeoraePlanArtifactRetentionStrictJson $value)){throw "$Label must be canonical JSON."};return $value }
function Assert-GeoraePlanArtifactRetentionExactProperties { param($Value,[string[]]$Expected,[string]$Label) $actual=@($Value.PSObject.Properties.Name|Sort-Object);$wanted=@($Expected|Sort-Object);if($actual.Count -ne $wanted.Count -or (@(Compare-Object $actual $wanted).Count -ne 0)){throw "$Label properties are not exact."} }
function Assert-GeoraePlanArtifactRetentionExactJson { param($Actual,$Expected,[string]$Label) if((ConvertTo-GeoraePlanArtifactRetentionStrictJson $Actual) -cne (ConvertTo-GeoraePlanArtifactRetentionStrictJson $Expected)){throw "$Label is not exact-idempotent."} }
function Assert-GeoraePlanArtifactRetentionJsonString { param($Value,[string]$Label) if($null -eq $Value -or $Value.GetType() -ne [string] -or [string]::IsNullOrWhiteSpace([string]$Value)){throw "$Label must be a non-empty JSON string."} }
function Assert-GeoraePlanArtifactRetentionJsonBoolean { param($Value,[string]$Label) if($null -eq $Value -or $Value.GetType() -ne [bool]){throw "$Label must be a JSON boolean."} }
function Assert-GeoraePlanArtifactRetentionJsonNonNegativeInteger { param($Value,[string]$Label) $types=@([byte],[sbyte],[int16],[uint16],[int32],[uint32],[int64],[uint64]);if($null -eq $Value -or $Value.GetType() -notin $types -or [decimal]$Value -lt 0 -or [decimal]$Value -gt [int64]::MaxValue){throw "$Label must be a non-negative JSON integer."} }
function Assert-GeoraePlanArtifactRetentionTestClosureEntrySchema {
 param($Entry)
 Assert-GeoraePlanArtifactRetentionExactProperties $Entry @('relativePath','kind','length','sha256') 'trusted test closure entry'
 Assert-GeoraePlanArtifactRetentionJsonString $Entry.relativePath 'trusted test closure relativePath'
 Assert-GeoraePlanArtifactRetentionJsonString $Entry.kind 'trusted test closure kind'
 if($Entry.kind -ceq 'directory'){
  if($null -ne $Entry.length -or $null -ne $Entry.sha256){throw 'Trusted test closure directory length and sha256 must be JSON null.'}
 }elseif($Entry.kind -ceq 'file'){
  Assert-GeoraePlanArtifactRetentionJsonNonNegativeInteger $Entry.length 'trusted test closure file length'
  Assert-GeoraePlanArtifactRetentionJsonString $Entry.sha256 'trusted test closure file sha256'
  if(([string]$Entry.sha256)-notmatch'^[0-9A-Fa-f]{64}$'){throw 'Trusted test closure file sha256 is not exact hexadecimal metadata.'}
 }else{throw 'Trusted test closure entry kind is invalid.'}
}
function ConvertFrom-GeoraePlanArtifactRetentionUtcTimestamp { param($Value,[string]$Label) Assert-GeoraePlanArtifactRetentionJsonString $Value $Label;$parsed=[DateTimeOffset]::MinValue;if(-not[DateTimeOffset]::TryParseExact([string]$Value,'o',[Globalization.CultureInfo]::InvariantCulture,[Globalization.DateTimeStyles]::RoundtripKind,[ref]$parsed) -or $parsed.Offset -ne [TimeSpan]::Zero){throw "$Label must be an exact UTC round-trip timestamp."};return $parsed }
function Assert-GeoraePlanArtifactRetentionParentProvisioningToken {
 param($Token,[string]$ExpectedPath,$Ancestor)
 Assert-GeoraePlanArtifactRetentionExactProperties $Token @('schemaVersion','kind','parentId','createdAtUtc','parentPath','ancestorPhysicalPath','ancestorVolumeSerialNumber','ancestorFileId') 'parent provisioning token'
 Assert-GeoraePlanArtifactRetentionJsonNonNegativeInteger $Token.schemaVersion 'parent provisioning token schemaVersion'
 foreach($field in @($Token.kind,$Token.parentId,$Token.createdAtUtc,$Token.parentPath,$Token.ancestorPhysicalPath,$Token.ancestorVolumeSerialNumber,$Token.ancestorFileId)){Assert-GeoraePlanArtifactRetentionJsonString $field 'parent provisioning token string field'}
 [void](ConvertFrom-GeoraePlanArtifactRetentionUtcTimestamp $Token.createdAtUtc 'parent provisioning token createdAtUtc')
 if([decimal]$Token.schemaVersion -ne 1 -or $Token.kind -cne 'georaeplan-artifact-parent-token-v1' -or $Token.parentId -notmatch '^[0-9a-f]{32}$' -or -not(Test-GeoraePlanArtifactRetentionPathEquals $Token.parentPath $ExpectedPath) -or -not(Test-GeoraePlanArtifactRetentionPathEquals $Token.ancestorPhysicalPath $Ancestor.PhysicalPath) -or $Token.ancestorVolumeSerialNumber -ine $Ancestor.VolumeSerialNumber -or $Token.ancestorFileId -ine $Ancestor.FileId){throw 'Parent provisioning token is invalid.'}
}
function Assert-GeoraePlanArtifactRetentionStageProvisioningToken {
 param($Token,[string]$ArtifactId,[string]$ParentId,[string]$ExpectedPath)
 Assert-GeoraePlanArtifactRetentionExactProperties $Token @('schemaVersion','kind','artifactId','parentId','stagePath','createdAtUtc') 'stage provisioning token'
 Assert-GeoraePlanArtifactRetentionJsonNonNegativeInteger $Token.schemaVersion 'stage provisioning token schemaVersion'
 foreach($field in @($Token.kind,$Token.artifactId,$Token.parentId,$Token.stagePath,$Token.createdAtUtc)){Assert-GeoraePlanArtifactRetentionJsonString $field 'stage provisioning token string field'}
 [void](ConvertFrom-GeoraePlanArtifactRetentionUtcTimestamp $Token.createdAtUtc 'stage provisioning token createdAtUtc')
 if([decimal]$Token.schemaVersion -ne 1 -or $Token.kind -cne 'georaeplan-artifact-stage-token-v1' -or $Token.artifactId -cne $ArtifactId -or $Token.parentId -cne $ParentId -or -not(Test-GeoraePlanArtifactRetentionPathEquals $Token.stagePath $ExpectedPath)){throw 'Stage provisioning token is invalid.'}
}
function Read-GeoraePlanArtifactRetentionStableBytes { param([string]$Path) $pin=Open-GeoraePlanArtifactRetentionStableFile $Path;try{$stream=New-Object IO.FileStream($pin.Path,[IO.FileMode]::Open,[IO.FileAccess]::Read,[IO.FileShare]::Read);try{$memory=New-Object IO.MemoryStream;$stream.CopyTo($memory);$bytes=$memory.ToArray();$memory.Dispose()}finally{$stream.Dispose()};Assert-GeoraePlanArtifactRetentionPinned $pin|Out-Null;return ,$bytes}finally{Close-GeoraePlanArtifactRetentionPinned $pin} }
function Get-GeoraePlanArtifactRetentionSha256 { param([byte[]]$Bytes) $sha=[Security.Cryptography.SHA256]::Create();try{return ([BitConverter]::ToString($sha.ComputeHash($Bytes))).Replace('-','')}finally{$sha.Dispose()} }
function New-GeoraePlanArtifactRetentionLease { param([string]$Path) return [IO.File]::Open($Path,[IO.FileMode]::CreateNew,[IO.FileAccess]::ReadWrite,[IO.FileShare]::ReadWrite) }
function Enter-GeoraePlanArtifactRetentionProducerLease { param([string]$LeasePath) Initialize-GeoraePlanArtifactRetentionProducerNativeType;$path=Get-GeoraePlanArtifactRetentionNormalizedPath $LeasePath;$lease=[GeoraePlan.ArtifactRetentionProducer.PinnedEntry]::OpenExclusiveFile($path);try{$identity=$lease.EntryIdentity;if($identity.IsDirectory -or $identity.IsReparsePoint -or $identity.Links -ne 1 -or -not(Test-GeoraePlanArtifactRetentionPathEquals $identity.FinalPath $path)){throw 'Exclusive producer coordinator identity is invalid.'};$lease.Validate($path);return $lease}catch{$lease.Dispose();throw} }
function Assert-GeoraePlanArtifactRetentionParent {
 param([string]$AllowedParent)
 $path=Get-GeoraePlanArtifactRetentionNormalizedPath $AllowedParent
 if(-not(Test-Path -LiteralPath $path -PathType Container)){throw 'Artifact parent is missing.'}
 $pin=Open-GeoraePlanArtifactRetentionPinned $path -StableDirectory;$markerLease=$null;$bootstrapLease=$null
 try{
  if(-not $pin.IsDirectory){throw 'Artifact parent is not a directory.'}
  Assert-GeoraePlanArtifactRetentionPrivateAcl $path
  $markerPath=Join-Path $path $script:GeoraePlanArtifactRetentionParentOwnerFileName
  $leasePath=Join-Path $path $script:GeoraePlanArtifactRetentionParentLeaseFileName
  if(-not(Test-Path $markerPath -PathType Leaf) -or -not(Test-Path $leasePath -PathType Leaf)){throw 'Artifact parent marker or coordinator is missing.'}
  $leasePin=Open-GeoraePlanArtifactRetentionRelativeEntry $pin $script:GeoraePlanArtifactRetentionParentLeaseFileName $false;try{Assert-GeoraePlanArtifactRetentionPrivateFileAcl $leasePin.Path;if((Read-GeoraePlanArtifactRetentionPinnedBytes $leasePin).Length -ne 0){throw 'Artifact parent coordinator is nonconforming.'}}finally{Close-GeoraePlanArtifactRetentionPinned $leasePin}
  $markerLease=Open-GeoraePlanArtifactRetentionRelativeEntry $pin $script:GeoraePlanArtifactRetentionParentOwnerFileName $false
  Assert-GeoraePlanArtifactRetentionPrivateFileAcl $markerLease.Path
  $m=Read-GeoraePlanArtifactRetentionPinnedStrictJson $markerLease 'parent marker'
  Assert-GeoraePlanArtifactRetentionExactProperties $m @('schemaVersion','owner','parentId','parentPath','parentPhysicalPath','parentVolumeSerialNumber','parentFileId') 'parent marker'
  if($m.schemaVersion -ne 1 -or $m.owner -cne $script:GeoraePlanArtifactRetentionParentOwnerKind -or ([string]$m.parentId) -notmatch '^[0-9a-f]{32}$' -or -not(Test-GeoraePlanArtifactRetentionPathEquals $m.parentPath $path) -or -not(Test-GeoraePlanArtifactRetentionPathEquals $m.parentPhysicalPath $pin.PhysicalPath) -or $m.parentVolumeSerialNumber -ine $pin.VolumeSerialNumber -or $m.parentFileId -ine $pin.FileId){throw 'Artifact parent marker does not bind the pinned parent.'}
  $ancestor=Open-GeoraePlanArtifactRetentionPinned (Split-Path -Parent $path)
  try{
   $bootstrapName='.georaeplan-parent-bootstrap-'+(Split-Path -Leaf $path)+'.json'
   $bootstrapPath=Join-Path $ancestor.Path $bootstrapName
   if(-not(Test-Path -LiteralPath $bootstrapPath -PathType Leaf)){throw 'Artifact parent bootstrap journal is missing.'}
   $bootstrapLease=Open-GeoraePlanArtifactRetentionRelativeEntry $ancestor $bootstrapName $false
   Assert-GeoraePlanArtifactRetentionPrivateFileAcl $bootstrapLease.Path
   $bootstrap=Read-GeoraePlanArtifactRetentionPinnedStrictJson $bootstrapLease 'parent bootstrap journal'
   Assert-GeoraePlanArtifactRetentionExactProperties $bootstrap @('schemaVersion','kind','parentPath','ownerSid','parentId','createdAtUtc','ancestorPhysicalPath','ancestorVolumeSerialNumber','ancestorFileId','parentPhysicalPath','parentVolumeSerialNumber','parentFileId','rootTokenSha256') 'parent bootstrap journal'
   if($bootstrap.schemaVersion -ne 1 -or $bootstrap.kind -cne 'georaeplan-artifact-parent-bootstrap-v1' -or -not(Test-GeoraePlanArtifactRetentionPathEquals $bootstrap.parentPath $path) -or $bootstrap.ownerSid -cne [Security.Principal.WindowsIdentity]::GetCurrent().User.Value -or $bootstrap.parentId -cne $m.parentId -or -not(Test-GeoraePlanArtifactRetentionPathEquals $bootstrap.ancestorPhysicalPath $ancestor.PhysicalPath) -or $bootstrap.ancestorVolumeSerialNumber -ine $ancestor.VolumeSerialNumber -or $bootstrap.ancestorFileId -ine $ancestor.FileId -or -not(Test-GeoraePlanArtifactRetentionPathEquals $bootstrap.parentPhysicalPath $pin.PhysicalPath) -or $bootstrap.parentVolumeSerialNumber -ine $pin.VolumeSerialNumber -or $bootstrap.parentFileId -ine $pin.FileId){throw 'Artifact parent bootstrap journal binding is invalid.'}
   $tokenBytes=$pin.NativeHandle.ReadExtendedAttribute($script:GeoraePlanArtifactRetentionParentEaName)
    $tokenRaw=[Text.UTF8Encoding]::new($false,$true).GetString($tokenBytes)
    $token=$tokenRaw|ConvertFrom-Json -ErrorAction Stop
    if($tokenRaw -cne (ConvertTo-GeoraePlanArtifactRetentionStrictJson $token)){throw 'Parent provisioning token is noncanonical.'}
    Assert-GeoraePlanArtifactRetentionParentProvisioningToken $token $path $ancestor
    if($token.parentId -cne $bootstrap.parentId -or $token.createdAtUtc -cne $bootstrap.createdAtUtc){throw 'Parent provisioning token does not bind the bootstrap journal.'}
   if((Get-GeoraePlanArtifactRetentionSha256 $tokenBytes) -ine [string]$bootstrap.rootTokenSha256){throw 'Artifact parent provisioning token hash is invalid.'}
  }finally{Close-GeoraePlanArtifactRetentionPinned $ancestor}
   Assert-GeoraePlanArtifactRetentionParentChildSet $pin
  $markerHash=Get-GeoraePlanArtifactRetentionSha256 (Read-GeoraePlanArtifactRetentionPinnedBytes $markerLease)
  $bootstrapHash=Get-GeoraePlanArtifactRetentionSha256 (Read-GeoraePlanArtifactRetentionPinnedBytes $bootstrapLease)
  $result=[pscustomobject]@{Path=$path;Identity=$pin;LeasePath=$leasePath;ParentId=[string]$m.parentId;MarkerLease=$markerLease;BootstrapLease=$bootstrapLease;MarkerSha256=$markerHash;BootstrapSha256=$bootstrapHash}
  $pin=$null;$markerLease=$null;$bootstrapLease=$null
  return $result
 }catch{Close-GeoraePlanArtifactRetentionPinned $pin;Close-GeoraePlanArtifactRetentionPinned $markerLease;Close-GeoraePlanArtifactRetentionPinned $bootstrapLease;throw}
}
function Assert-GeoraePlanArtifactRetentionParentChildSet { param($PinnedParent,$ExclusiveCoordinator) $children=New-Object Collections.Generic.List[object];try{$records=if($null -eq $ExclusiveCoordinator){@($PinnedParent.NativeHandle.EnumerateAndOpenChildren($PinnedParent.Path,'parent'))}else{if($ExclusiveCoordinator.EntryIdentity.VolumeSerialNumber -ine $PinnedParent.VolumeSerialNumber){throw 'Exclusive producer coordinator volume is invalid.'};@($PinnedParent.NativeHandle.EnumerateAndOpenChildrenExceptHeld($PinnedParent.Path,$script:GeoraePlanArtifactRetentionParentLeaseFileName,$ExclusiveCoordinator,'parent'))};foreach($record in $records){if($null -ne $record.Entry){$child=ConvertFrom-GeoraePlanArtifactRetentionNativeChild $PinnedParent $record;[void]$children.Add($child)};$name=$record.Name;$known=($name -in @($script:GeoraePlanArtifactRetentionParentOwnerFileName,$script:GeoraePlanArtifactRetentionParentLeaseFileName) -or $name -match '^\.georaeplan-producer-stage-[0-9a-f]{32}$' -or $name -match '^\.georaeplan-producer-finalize-[0-9a-f]{32}\.json$' -or $name -match '^[0-9a-f]{32}$' -or $name -match '^\.georaeplan-retention-[0-9a-f]{32}-[0-9a-f]{32}\.quarantine$');if(-not$known){throw 'Artifact parent contains an unknown entry.'}}}finally{for($i=$children.Count-1;$i -ge 0;$i--){Close-GeoraePlanArtifactRetentionPinned $children[$i]}} }
function Assert-GeoraePlanArtifactRetentionParentUnchanged { param($Parent,[string]$ExpectedMarkerSha256,$ExclusiveCoordinator) Assert-GeoraePlanArtifactRetentionPinned $Parent.Identity|Out-Null;Assert-GeoraePlanArtifactRetentionPinned $Parent.MarkerLease|Out-Null;Assert-GeoraePlanArtifactRetentionPinned $Parent.BootstrapLease|Out-Null;$ExclusiveCoordinator.Validate($Parent.LeasePath);if((Get-GeoraePlanArtifactRetentionSha256 (Read-GeoraePlanArtifactRetentionPinnedBytes $Parent.MarkerLease)) -ine $ExpectedMarkerSha256 -or (Get-GeoraePlanArtifactRetentionSha256 (Read-GeoraePlanArtifactRetentionPinnedBytes $Parent.BootstrapLease)) -ine $Parent.BootstrapSha256){throw 'Artifact parent durable metadata changed.'};Assert-GeoraePlanArtifactRetentionParentChildSet $Parent.Identity $ExclusiveCoordinator }
function Close-GeoraePlanArtifactRetentionParent { param($Parent) if($null -ne $Parent){Close-GeoraePlanArtifactRetentionPinned $Parent.MarkerLease;Close-GeoraePlanArtifactRetentionPinned $Parent.BootstrapLease;Close-GeoraePlanArtifactRetentionPinned $Parent.Identity} }
function Get-GeoraePlanArtifactRetentionConsumerExpectedEntries { param($Plan,[byte[]]$ProducerManifestBytes) $entries=New-Object Collections.Generic.List[object];foreach($item in @($Plan)){if($item.kind -ceq 'directory'){$entries.Add([ordered]@{relativePath=[string]$item.relativePath;kind='directory';sha256=$null})}else{$entries.Add([ordered]@{relativePath=[string]$item.relativePath;kind='file';sha256=[string]$item.sha256})}};$entries.Add([ordered]@{relativePath=$script:GeoraePlanArtifactRetentionProducerManifestFileName;kind='file';sha256=(Get-GeoraePlanArtifactRetentionSha256 $ProducerManifestBytes)});return @($entries.ToArray()|Sort-Object {$_.relativePath}) }
function Add-GeoraePlanArtifactRetentionFinalConsumerTree { param($PinnedDirectory,[string]$Prefix,$Items,$Handles) foreach($record in @($PinnedDirectory.NativeHandle.EnumerateAndOpenChildren($PinnedDirectory.Path,'final-subset'))){$child=ConvertFrom-GeoraePlanArtifactRetentionNativeChild $PinnedDirectory $record;[void]$Handles.Add($child);if([string]::IsNullOrEmpty($Prefix) -and $record.Name -in @($script:GeoraePlanArtifactRetentionOwnerFileName,$script:GeoraePlanArtifactRetentionCompletionFileName)){continue};$relative=if([string]::IsNullOrEmpty($Prefix)){$record.Name}else{$Prefix+'/'+$record.Name};if($child.IsDirectory){[void]$Items.Add([ordered]@{relativePath=$relative;kind='directory';sha256=$null});Add-GeoraePlanArtifactRetentionFinalConsumerTree $child $relative $Items $Handles}else{$bytes=Read-GeoraePlanArtifactRetentionPinnedBytes $child;[void]$Items.Add([ordered]@{relativePath=$relative;kind='file';sha256=(Get-GeoraePlanArtifactRetentionSha256 $bytes)})}} }
function Get-GeoraePlanArtifactRetentionHeldFinalConsumerTree { param($PinnedFinal,$ExpectedEntries) $items=New-Object Collections.Generic.List[object];$handles=New-Object Collections.Generic.List[object];try{Add-GeoraePlanArtifactRetentionFinalConsumerTree $PinnedFinal '' $items $handles;$actual=@($items.ToArray()|Sort-Object {$_.relativePath});if((ConvertTo-GeoraePlanArtifactRetentionStrictJson $actual) -cne (ConvertTo-GeoraePlanArtifactRetentionStrictJson @($ExpectedEntries))){throw 'Completed artifact tree differs from the exact consumer entries.'};return [pscustomobject]@{Items=$actual;Handles=$handles}}catch{for($i=$handles.Count-1;$i-ge0;$i--){Close-GeoraePlanArtifactRetentionPinned $handles[$i]};throw} }
function Add-GeoraePlanArtifactRetentionRelativePlan { param($PinnedDirectory,[string]$Prefix,$Items,$Handles,[switch]$IncludeAll) Assert-GeoraePlanArtifactRetentionPinned $PinnedDirectory|Out-Null;$children=New-Object Collections.Generic.List[object];try{foreach($record in @($PinnedDirectory.NativeHandle.EnumerateAndOpenChildren($PinnedDirectory.Path,'source'))){$child=ConvertFrom-GeoraePlanArtifactRetentionNativeChild $PinnedDirectory $record;[void]$children.Add([pscustomobject]@{Name=$record.Name;Pinned=$child});[void]$Handles.Add($child)};foreach($entry in $children){if(-not$IncludeAll -and $entry.Name -eq '.georaeplan-producer-stage.json' -and [string]::IsNullOrEmpty($Prefix)){continue};$child=$entry.Pinned;$relative=if([string]::IsNullOrEmpty($Prefix)){$entry.Name}else{$Prefix+'/'+$entry.Name};if($child.IsDirectory){$Items.Add([pscustomobject][ordered]@{relativePath=$relative;kind='directory';length=[int64]0;sha256=$null;SourcePinned=$child});Add-GeoraePlanArtifactRetentionRelativePlan $child $relative $Items $Handles -IncludeAll:$IncludeAll}else{$bytes=Read-GeoraePlanArtifactRetentionPinnedBytes $child;$Items.Add([pscustomobject][ordered]@{relativePath=$relative;kind='file';length=[int64]$bytes.Length;sha256=(Get-GeoraePlanArtifactRetentionSha256 $bytes);SourcePinned=$child})}}}catch{throw};Assert-GeoraePlanArtifactRetentionPinned $PinnedDirectory|Out-Null }
function Get-GeoraePlanArtifactRetentionMaterializationPlan { param($PinnedSource) $items=New-Object Collections.Generic.List[object];$handles=New-Object Collections.Generic.List[object];try{Add-GeoraePlanArtifactRetentionRelativePlan $PinnedSource '' $items $handles;$sorted=@($items.ToArray()|Sort-Object {$_.relativePath});return [pscustomobject]@{Items=$sorted;Handles=$handles}}catch{for($i=$handles.Count-1;$i -ge 0;$i--){Close-GeoraePlanArtifactRetentionPinned $handles[$i]};throw} }
function Get-GeoraePlanArtifactRetentionExactClosurePlan { param($PinnedSource) $items=New-Object Collections.Generic.List[object];$handles=New-Object Collections.Generic.List[object];try{Add-GeoraePlanArtifactRetentionRelativePlan $PinnedSource '' $items $handles -IncludeAll;$sorted=@($items.ToArray()|Sort-Object {$_.relativePath});return [pscustomobject]@{Items=$sorted;Handles=$handles}}catch{for($i=$handles.Count-1;$i -ge 0;$i--){Close-GeoraePlanArtifactRetentionPinned $handles[$i]};throw} }
function Close-GeoraePlanArtifactRetentionHeldTree { param($HeldTree) if($null -ne $HeldTree){for($i=$HeldTree.Handles.Count-1;$i -ge 0;$i--){Close-GeoraePlanArtifactRetentionPinned $HeldTree.Handles[$i]}} }
function Get-GeoraePlanArtifactRetentionJournalPlan { param($Plan) return @($Plan|ForEach-Object{[ordered]@{relativePath=[string]$_.relativePath;kind=[string]$_.kind;length=[int64]$_.length;sha256=$_.sha256;volumeSerialNumber=[string]$_.SourcePinned.VolumeSerialNumber;fileId=[string]$_.SourcePinned.FileId}}) }
function Assert-GeoraePlanArtifactRetentionMaterializationPlan {
 param($PinnedSource,$ExpectedPlan)
 foreach($item in @($ExpectedPlan)){Assert-GeoraePlanArtifactRetentionPinned $item.SourcePinned|Out-Null;if($item.kind -ceq 'file'){$bytes=Read-GeoraePlanArtifactRetentionPinnedBytes $item.SourcePinned;if($bytes.Length -ne [int64]$item.length -or (Get-GeoraePlanArtifactRetentionSha256 $bytes) -cne [string]$item.sha256){throw 'Held artifact source file changed.'}}}
 $fresh=$null;try{$fresh=Get-GeoraePlanArtifactRetentionMaterializationPlan $PinnedSource;if((ConvertTo-GeoraePlanArtifactRetentionStrictJson (Get-GeoraePlanArtifactRetentionJournalPlan $fresh.Items)) -cne (ConvertTo-GeoraePlanArtifactRetentionStrictJson (Get-GeoraePlanArtifactRetentionJournalPlan $ExpectedPlan))){throw 'Artifact source changed after finalize journal creation.'}}finally{Close-GeoraePlanArtifactRetentionHeldTree $fresh}
}
function Assert-GeoraePlanArtifactRetentionExactClosurePlan {
 param($PinnedSource,$ExpectedPlan)
 foreach($item in @($ExpectedPlan)){Assert-GeoraePlanArtifactRetentionPinned $item.SourcePinned|Out-Null;if($item.kind -ceq 'file'){$bytes=Read-GeoraePlanArtifactRetentionPinnedBytes $item.SourcePinned;if($bytes.Length -ne [int64]$item.length -or (Get-GeoraePlanArtifactRetentionSha256 $bytes) -cne [string]$item.sha256){throw 'Held test dependency file changed.'}}}
 $fresh=$null;try{$fresh=Get-GeoraePlanArtifactRetentionExactClosurePlan $PinnedSource;if((ConvertTo-GeoraePlanArtifactRetentionStrictJson (Get-GeoraePlanArtifactRetentionJournalPlan $fresh.Items)) -cne (ConvertTo-GeoraePlanArtifactRetentionStrictJson (Get-GeoraePlanArtifactRetentionJournalPlan $ExpectedPlan))){throw 'Test execution dependency tree changed.'}}finally{Close-GeoraePlanArtifactRetentionHeldTree $fresh}
}
function Get-GeoraePlanArtifactRetentionPlanItem { param($Plan,[string]$RelativePath) foreach($item in @($Plan)){if(([string]$item.relativePath) -ceq $RelativePath){return $item}};return $null }
function Assert-GeoraePlanArtifactRetentionFinalSubsetDirectory { param($PinnedDirectory,[string]$Prefix,$Plan,[string[]]$MetadataNames) $heldChildren=New-Object Collections.Generic.List[object];try{foreach($record in @($PinnedDirectory.NativeHandle.EnumerateAndOpenChildren($PinnedDirectory.Path,'final-subset'))){$held=ConvertFrom-GeoraePlanArtifactRetentionNativeChild $PinnedDirectory $record;[void]$heldChildren.Add([pscustomobject]@{Name=$record.Name;Pinned=$held})};foreach($entry in $heldChildren){$held=$entry.Pinned;$relative=if([string]::IsNullOrEmpty($Prefix)){$entry.Name}else{$Prefix+'/'+$entry.Name};if(-not$held.IsDirectory -and [string]::IsNullOrEmpty($Prefix) -and $relative -in $MetadataNames){Assert-GeoraePlanArtifactRetentionPrivateFileAcl $held.Path;continue};$expected=Get-GeoraePlanArtifactRetentionPlanItem $Plan $relative;if($null -eq $expected){throw 'Partial artifact contains an unknown entry.'};if($held.IsDirectory){if($expected.kind -cne 'directory'){throw 'Partial artifact entry type is invalid.'};Assert-GeoraePlanArtifactRetentionPrivateAcl $held.Path;Assert-GeoraePlanArtifactRetentionFinalSubsetDirectory $held $relative $Plan $MetadataNames}else{if($expected.kind -cne 'file'){throw 'Partial artifact entry type is invalid.'};Assert-GeoraePlanArtifactRetentionPrivateFileAcl $held.Path;$bytes=Read-GeoraePlanArtifactRetentionPinnedBytes $held;$sourceBytes=Read-GeoraePlanArtifactRetentionPinnedBytes $expected.SourcePinned;if($bytes.Length -gt [int64]$expected.length){throw 'Partial artifact file is longer than expected.'};for($prefixIndex=0;$prefixIndex -lt $bytes.Length;$prefixIndex++){if($bytes[$prefixIndex] -ne $sourceBytes[$prefixIndex]){throw 'Partial artifact file is not an exact expected prefix.'}}}}}finally{for($i=$heldChildren.Count-1;$i -ge 0;$i--){Close-GeoraePlanArtifactRetentionPinned $heldChildren[$i].Pinned}} }
function Assert-GeoraePlanArtifactRetentionFinalSubset { param($PinnedFinal,$Plan,[string[]]$MetadataNames) Assert-GeoraePlanArtifactRetentionPinned $PinnedFinal|Out-Null;Assert-GeoraePlanArtifactRetentionFinalSubsetDirectory $PinnedFinal '' $Plan $MetadataNames;Assert-GeoraePlanArtifactRetentionPinned $PinnedFinal|Out-Null }
function Copy-GeoraePlanArtifactRetentionPlanItem {
 param($PinnedFinal,$Item,$DestinationLeases,[string]$TestFaultInjection)
 $segments=@(([string]$Item.relativePath).Split('/'))
 if($segments.Count -eq 0 -or @($segments|Where-Object{[string]::IsNullOrWhiteSpace($_) -or $_ -eq '.' -or $_ -eq '..'}).Count -ne 0){throw 'Materialization plan contains an unsafe relative path.'}
 $current=$PinnedFinal;$opened=New-Object Collections.Generic.List[object]
 try{
  for($index=0;$index -lt $segments.Count-1;$index++){
   $childPath=Join-Path $current.Path $segments[$index]
   if(Test-Path -LiteralPath $childPath){$child=Open-GeoraePlanArtifactRetentionRelativeEntry $current $segments[$index] $true;Assert-GeoraePlanArtifactRetentionPrivateAcl $childPath}
   else{$child=New-GeoraePlanArtifactRetentionRelativeDirectory $current $segments[$index]}
   $opened.Add($child);$DestinationLeases.Add($child);$current=$child
  }
  $leaf=$segments[$segments.Count-1];$destination=Join-Path $current.Path $leaf
  if($Item.kind -ceq 'directory'){
   if(Test-Path -LiteralPath $destination){$existing=Open-GeoraePlanArtifactRetentionRelativeEntry $current $leaf $true;Assert-GeoraePlanArtifactRetentionPrivateAcl $destination;$DestinationLeases.Add($existing)}
   else{$created=New-GeoraePlanArtifactRetentionRelativeDirectory $current $leaf;$DestinationLeases.Add($created)}
  } elseif($Item.kind -ceq 'file') {
   $bytes=Read-GeoraePlanArtifactRetentionPinnedBytes $Item.SourcePinned
   if($bytes.Length -ne [int64]$Item.length -or (Get-GeoraePlanArtifactRetentionSha256 $bytes) -cne [string]$Item.sha256){throw 'Artifact source file changed during materialization.'}
    $payloadPartial=if($TestFaultInjection -eq 'PartialPayloadOneByte' -and -not(Test-Path -LiteralPath $destination)){1}else{-1};$ensured=Write-GeoraePlanArtifactRetentionRelativeCreateNewBytes $current $leaf $bytes $payloadPartial;$DestinationLeases.Add($ensured)
  } else {throw 'Materialization plan kind is invalid.'}
 } finally { }
}
function Get-GeoraePlanArtifactRetentionFinalMetadataNames { return @($script:GeoraePlanArtifactRetentionOwnerFileName,$script:GeoraePlanArtifactRetentionProducerManifestFileName,$script:GeoraePlanArtifactRetentionCompletionFileName) }
function Invoke-GeoraePlanArtifactRetentionMaterialization { param($PinnedSource,$PinnedFinal,$Plan,$DestinationLeases,[string]$TestFaultInjection) Assert-GeoraePlanArtifactRetentionFinalSubset $PinnedFinal $Plan @(Get-GeoraePlanArtifactRetentionFinalMetadataNames);foreach($item in @($Plan)){Copy-GeoraePlanArtifactRetentionPlanItem $PinnedFinal $item $DestinationLeases $TestFaultInjection};Assert-GeoraePlanArtifactRetentionMaterializationPlan $PinnedSource $Plan;Assert-GeoraePlanArtifactRetentionFinalSubset $PinnedFinal $Plan @(Get-GeoraePlanArtifactRetentionFinalMetadataNames) }
function Test-GeoraePlanArtifactRetentionFault { param([string]$Name,[string]$Requested) if($Requested -eq $Name){if($env:GEORAEPLAN_ARTIFACT_PRODUCER_TEST_MODE -ne '1'){throw 'Fault injection is test-mode only.'};throw "Injected producer fault: $Name"} }
function Invoke-GeoraePlanArtifactRetentionTestStageSwap { param([string]$StagePath,$PinnedStage,[string]$Destination,[string]$Requested) if($Requested -ne 'SwapStageNameBeforePublish'){return $false};if($env:GEORAEPLAN_ARTIFACT_PRODUCER_TEST_MODE -ne '1'){throw 'Fault injection is test-mode only.'};$moved=$StagePath+'.swapped';$command="[IO.Directory]::Move('"+$StagePath.Replace("'","''")+"','"+$moved.Replace("'","''")+"')";$encoded=[Convert]::ToBase64String([Text.Encoding]::Unicode.GetBytes($command));$process=Start-Process -FilePath "$env:SystemRoot\System32\WindowsPowerShell\v1.0\powershell.exe" -ArgumentList @('-NoProfile','-EncodedCommand',$encoded) -WindowStyle Hidden -Wait -PassThru;if($process.ExitCode -eq 0 -or (Test-Path -LiteralPath $moved)){throw 'External stage name substitution unexpectedly succeeded.'};Assert-GeoraePlanArtifactRetentionPinned $PinnedStage|Out-Null;return $true }

function Get-GeoraePlanArtifactRetentionConsumerReservedNames {
 return @('.georaeplan-runtime-ready','.georaeplan-runtime-invalid','.georaeplan-prepare.lock','.georaeplan-prepare-gate.lock','.georaeplan-artifact.active.lease','.georaeplan-artifact-process.json','Run-All.cmd','Run-All.ps1','Run-App.cmd','Run-Server.cmd','Launch-Test-App.vbs')
}
function Assert-GeoraePlanArtifactRetentionConsumerMetadataBytes { param([byte[]]$Bytes) if($null -eq $Bytes -or $Bytes.Length -gt 65536){throw 'Artifact completion metadata exceeds the consumer limit.'} }
function Assert-GeoraePlanArtifactRetentionConsumerPlan {
 param($Plan)
 $reserved=@(Get-GeoraePlanArtifactRetentionConsumerReservedNames);$seen=New-Object 'Collections.Generic.HashSet[string]' ([StringComparer]::OrdinalIgnoreCase)
 foreach($item in @($Plan)){
  if($null -eq $item -or $item.kind -notin @('file','directory')){throw 'Artifact plan kind is outside the consumer contract.'}
  $relative=[string]$item.relativePath
  if([string]::IsNullOrWhiteSpace($relative) -or $relative.Contains('\') -or $relative.StartsWith('/') -or $relative.EndsWith('/')){throw 'Artifact plan relative path is outside the consumer contract.'}
  if(-not$seen.Add($relative)){throw 'Artifact plan contains a case-insensitive duplicate.'}
  $segments=$relative.Split('/')
  if(@($segments|Where-Object{[string]::IsNullOrWhiteSpace($_) -or $_ -in @('.','..')}).Count -ne 0){throw 'Artifact plan contains an unsafe segment.'}
  foreach($segment in $segments){if($segment -iin $reserved -or $segment -imatch '(?:\.pid|\.lock|\.lck|\.lease)$'){throw 'Artifact plan contains a consumer-reserved entry.'}}
  if($segments.Count -eq 1 -and $segments[0] -iin @($script:GeoraePlanArtifactRetentionOwnerFileName,$script:GeoraePlanArtifactRetentionCompletionFileName,$script:GeoraePlanArtifactRetentionProducerManifestFileName)){throw 'Artifact plan collides with root metadata.'}
 }
}
function Get-GeoraePlanArtifactRetentionPlanItemExact { param($Plan,[string]$RelativePath) foreach($item in @($Plan)){if(([string]$item.relativePath) -ceq $RelativePath){return $item}};return $null }
function Add-GeoraePlanArtifactRetentionHeldStageCleanupDirectory {
 param($PinnedDirectory,[string]$Prefix,$JournalPlan,[string]$StageMarkerSha256,[string]$StageMarkerVolumeSerialNumber,[string]$StageMarkerFileId,$DeleteOrder,[switch]$AllowMissing)
 $records=New-Object Collections.Generic.List[object]
 try{
  foreach($record in @($PinnedDirectory.NativeHandle.EnumerateAndOpenChildrenForCleanup($PinnedDirectory.Path))){$child=ConvertFrom-GeoraePlanArtifactRetentionNativeChild $PinnedDirectory $record;[void]$records.Add([pscustomobject]@{Name=$record.Name;Pinned=$child})}
  foreach($record in $records){
   $child=$record.Pinned;$relative=if([string]::IsNullOrEmpty($Prefix)){$record.Name}else{$Prefix+'/'+$record.Name}
   if([string]::IsNullOrEmpty($Prefix) -and $record.Name -ceq '.georaeplan-producer-stage.json'){
    if($child.IsDirectory -or $child.VolumeSerialNumber -ine $StageMarkerVolumeSerialNumber -or $child.FileId -ine $StageMarkerFileId){throw 'Stage marker cleanup identity is invalid.'}
    Assert-GeoraePlanArtifactRetentionPrivateFileAcl $child.Path
    if((Get-GeoraePlanArtifactRetentionSha256 (Read-GeoraePlanArtifactRetentionPinnedBytes $child)) -ine $StageMarkerSha256){throw 'Stage marker cleanup bytes changed.'}
    continue
   }
   $expected=Get-GeoraePlanArtifactRetentionPlanItemExact $JournalPlan $relative
   if($null -eq $expected){throw 'Stage cleanup found an unknown entry.'}
   if($child.IsDirectory -ne ($expected.kind -ceq 'directory') -or $child.VolumeSerialNumber -ine [string]$expected.volumeSerialNumber -or $child.FileId -ine [string]$expected.fileId){throw 'Stage cleanup entry identity is invalid.'}
   if(-not$child.IsDirectory){$bytes=Read-GeoraePlanArtifactRetentionPinnedBytes $child;if($bytes.Length -ne [int64]$expected.length -or (Get-GeoraePlanArtifactRetentionSha256 $bytes) -ine [string]$expected.sha256){throw 'Stage cleanup file bytes changed.'}}
  }
  if(-not$AllowMissing){
   $actual=@($records|ForEach-Object{if([string]::IsNullOrEmpty($Prefix)){$_.Name}else{$Prefix+'/'+$_.Name}}|Where-Object{$_ -cne '.georaeplan-producer-stage.json'}|Sort-Object)
   $wanted=@($JournalPlan|Where-Object{if([string]::IsNullOrEmpty($Prefix)){([string]$_.relativePath).IndexOf('/') -lt 0}else{([string]$_.relativePath).StartsWith($Prefix+'/',[StringComparison]::Ordinal) -and ([string]$_.relativePath).Substring($Prefix.Length+1).IndexOf('/') -lt 0}}|ForEach-Object{$_.relativePath}|Sort-Object)
   if($actual.Count -ne $wanted.Count -or @(Compare-Object $actual $wanted).Count -ne 0){throw 'Stage cleanup exact child set is incomplete.'}
  }
  foreach($record in @($records|Where-Object{-not$_.Pinned.IsDirectory})){[void]$DeleteOrder.Add($record.Pinned);$record.Pinned=$null}
  foreach($record in @($records|Where-Object{$null -ne $_.Pinned -and $_.Pinned.IsDirectory})){$relative=if([string]::IsNullOrEmpty($Prefix)){$record.Name}else{$Prefix+'/'+$record.Name};Add-GeoraePlanArtifactRetentionHeldStageCleanupDirectory $record.Pinned $relative $JournalPlan $StageMarkerSha256 $StageMarkerVolumeSerialNumber $StageMarkerFileId $DeleteOrder -AllowMissing:$AllowMissing;[void]$DeleteOrder.Add($record.Pinned);$record.Pinned=$null}
 }finally{foreach($record in $records){if($null -ne $record.Pinned){Close-GeoraePlanArtifactRetentionPinned $record.Pinned}}}
}
function New-GeoraePlanArtifactRetentionHeldStageCleanupPlan {
 param($Parent,$ExclusiveCoordinator,[string]$StageName,$StageIdentity,$JournalPlan,[string]$StageMarkerSha256,[string]$StageMarkerVolumeSerialNumber,[string]$StageMarkerFileId,[switch]$AllowMissing)
 $stage=$null;$order=New-Object Collections.Generic.List[object]
 try{
  try{$stage=Open-GeoraePlanArtifactRetentionRelativeEntryForCleanup $Parent.Identity $StageName $true}catch{if($AllowMissing){Assert-GeoraePlanArtifactRetentionParentChildSet $Parent.Identity $ExclusiveCoordinator;return [pscustomobject]@{Entries=$order;Missing=$true}};throw}
  if($stage.VolumeSerialNumber -ine [string]$StageIdentity.VolumeSerialNumber -or $stage.FileId -ine [string]$StageIdentity.FileId){throw 'Stage cleanup root identity is invalid.'}
  Assert-GeoraePlanArtifactRetentionPrivateAcl $stage.Path
  $token=$stage.NativeHandle.ReadExtendedAttribute($script:GeoraePlanArtifactRetentionStageEaName);if((Get-GeoraePlanArtifactRetentionSha256 $token) -ine [string]$StageIdentity.TokenSha256){throw 'Stage cleanup provisioning token changed.'}
  Add-GeoraePlanArtifactRetentionHeldStageCleanupDirectory $stage '' $JournalPlan $StageMarkerSha256 $StageMarkerVolumeSerialNumber $StageMarkerFileId $order -AllowMissing:$AllowMissing
  [void]$order.Add($stage);$stage=$null
  return [pscustomobject]@{Entries=$order;Missing=$false}
 }catch{for($i=$order.Count-1;$i-ge0;$i--){Close-GeoraePlanArtifactRetentionPinned $order[$i]};throw}finally{Close-GeoraePlanArtifactRetentionPinned $stage}
}
function Close-GeoraePlanArtifactRetentionHeldStageCleanupPlan {
 param($Plan,[switch]$Commit,[string]$Fault='')
 if($null -eq $Plan){return}
 if(-not$Commit){for($i=0;$i-lt$Plan.Entries.Count;$i++){Close-GeoraePlanArtifactRetentionPinned $Plan.Entries[$i]};$Plan.Entries.Clear();return}
 $committed=0
 try{foreach($entry in @($Plan.Entries|Where-Object{-not$_.IsDirectory})){$entry.NativeHandle.MarkDelete();Close-GeoraePlanArtifactRetentionPinned $entry;$committed++;if($committed-eq1-and$Fault-ceq'FailAfterFirstCleanupCommit'){throw 'Injected failure after first cleanup commit.'}};foreach($entry in @($Plan.Entries|Where-Object{$_.IsDirectory})){$entry.NativeHandle.MarkDelete();Close-GeoraePlanArtifactRetentionPinned $entry}}finally{foreach($entry in $Plan.Entries){Close-GeoraePlanArtifactRetentionPinned $entry};$Plan.Entries.Clear()}
}
