[CmdletBinding()]
param(
    [string]$ProjectRoot,
    [string]$ChecklistPath,
    [string]$ChangedFilesPath,
    [string]$LogRoot,
    [string]$CommitMessage,
    [string]$Remote = 'origin',
    [string[]]$IncludeUntrackedPaths = @(),
    [string[]]$IncludeTrackedPaths = @(),
    [ValidateRange(0, 2147483647)][int]$KeepReleaseCount = 0,
    [ValidateRange(1, 3600)][int]$ReleaseHealthTimeoutSeconds = 900,
    [ValidateRange(1, 3600)][int]$RollbackHealthTimeoutSeconds = 900,
    [switch]$SkipLinuxPc,
    [switch]$SkipGit,
    [switch]$SkipPush,
    [switch]$DryRun,
    [switch]$AllowLegacyLiveMirror,
    [switch]$AllowScheduledApplyTrigger,
    [string]$LinuxSshHost,
    [string]$LinuxSshUser,
    [int]$LinuxSshPort = 0,
    [string]$LinuxSshKeyPath,
    [string]$LinuxRemoteOpsPath,
    [switch]$SkipPreDeployOperationalGate,
    [switch]$SkipPostDeployOperationalGate,
    [switch]$FailOnOperationalWarnings,
    [switch]$AcceptRentalTemplateItemReferenceRisk,
    [switch]$PreserveLiveAndroidUpdate,
    [switch]$SkipAndroidSigningContinuityCheck,
    [switch]$AcceptAndroidSigningCertificateChange,
    [string]$LocalCacheAppDataRoot = '',
    [string]$LocalCacheEvidenceDirectory = '',
    [switch]$RequireLocalCacheConsistencyCheck,
    [switch]$FailOnLocalCacheWarning,
    [string]$PreDeployBaseUrl = '',
    [string]$PreDeploySecretPath = '',
    [string]$PreDeployOutputDirectory = '',
    [string[]]$PreDeployAllowedIntegrityWarningCodes = @(),
    [string]$PostDeployBaseUrl = '',
    [string]$PostDeploySecretPath = '',
    [string]$PostDeployOutputDirectory = '',
    [string[]]$PostDeployAllowedIntegrityWarningCodes = @()
)

$scriptPath = Join-Path $PSScriptRoot 'Deploy-After-Test.ps1'
& $scriptPath @PSBoundParameters
exit $LASTEXITCODE
